2021-11-28 20:17:15.953 CET [28424] LOG:  could not bind IPv6 address "::1": Permission denied
2021-11-28 20:17:15.953 CET [28424] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2021-11-28 20:17:15.953 CET [28424] LOG:  could not bind IPv4 address "127.0.0.1": Permission denied
2021-11-28 20:17:15.953 CET [28424] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2021-11-28 20:17:15.953 CET [28424] WARNING:  could not create listen socket for "localhost"
2021-11-28 20:17:15.953 CET [28424] FATAL:  could not create any TCP/IP sockets
2021-11-28 20:17:15.953 CET [28424] LOG:  database system is shut down
2021-11-28 20:18:27.480 CET [33524] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:18:27.480 CET [33524] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:18:27.527 CET [32888] LOG:  database system was shut down at 2021-11-28 20:17:14 CET
2021-11-28 20:18:27.645 CET [33524] LOG:  database system is ready to accept connections
2021-11-28 20:18:30.041 CET [33524] LOG:  server process (PID 22148) was terminated by exception 0xC000013A
2021-11-28 20:18:30.041 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:30.041 CET [33524] LOG:  terminating any other active server processes
2021-11-28 20:18:30.049 CET [33524] LOG:  statistics collector process (PID 12872) was terminated by exception 0xC000013A
2021-11-28 20:18:30.049 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:30.050 CET [33524] LOG:  all server processes terminated; reinitializing
2021-11-28 20:18:30.101 CET [18040] LOG:  database system was interrupted; last known up at 2021-11-28 20:18:27 CET
2021-11-28 20:18:30.358 CET [18040] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:18:30.360 CET [18040] LOG:  invalid record length at 0/1628578: wanted 24, got 0
2021-11-28 20:18:30.360 CET [18040] LOG:  redo is not required
2021-11-28 20:18:30.489 CET [33524] LOG:  database system is ready to accept connections
2021-11-28 20:18:39.122 CET [33524] LOG:  worker process: logical replication launcher (PID 28864) was terminated by exception 0xC000013A
2021-11-28 20:18:39.122 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:39.123 CET [33524] LOG:  terminating any other active server processes
2021-11-28 20:18:39.127 CET [33524] LOG:  statistics collector process (PID 21568) was terminated by exception 0xC000013A
2021-11-28 20:18:39.127 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:39.129 CET [33524] LOG:  all server processes terminated; reinitializing
2021-11-28 20:18:39.172 CET [33160] LOG:  database system was interrupted; last known up at 2021-11-28 20:18:30 CET
2021-11-28 20:18:39.425 CET [33160] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:18:39.427 CET [33160] LOG:  invalid record length at 0/16285E8: wanted 24, got 0
2021-11-28 20:18:39.427 CET [33160] LOG:  redo is not required
2021-11-28 20:18:39.549 CET [33524] LOG:  database system is ready to accept connections
2021-11-28 20:18:40.309 CET [26892] ERROR:  canceling statement due to user request
2021-11-28 20:18:40.309 CET [3640] ERROR:  canceling statement due to user request
2021-11-28 20:18:40.311 CET [33524] LOG:  received fast shutdown request
2021-11-28 20:18:40.314 CET [33524] LOG:  aborting any active transactions
2021-11-28 20:18:40.316 CET [33524] LOG:  worker process: logical replication launcher (PID 26892) exited with exit code 1
2021-11-28 20:18:40.331 CET [20180] LOG:  shutting down
2021-11-28 20:18:40.348 CET [33524] LOG:  database system is shut down
2021-11-28 20:18:47.499 CET [10672] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:18:47.499 CET [10672] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:18:47.545 CET [10656] LOG:  database system was shut down at 2021-11-28 20:18:40 CET
2021-11-28 20:18:47.663 CET [10672] LOG:  database system is ready to accept connections
2021-11-28 20:20:48.274 CET [12624] ERROR:  permission denied to create database
2021-11-28 20:20:48.274 CET [12624] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:20:48.315 CET [30588] FATAL:  database "mtcg" does not exist
2021-11-28 20:21:12.397 CET [18588] ERROR:  permission denied to create database
2021-11-28 20:21:12.397 CET [18588] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:21:12.438 CET [5952] FATAL:  database "mockdb" does not exist
2021-11-28 20:21:36.586 CET [31900] ERROR:  permission denied to create database
2021-11-28 20:21:36.586 CET [31900] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:21:40.059 CET [31900] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:23:36.123 CET [22868] ERROR:  permission denied to create extension "uuid-ossp"
2021-11-28 20:23:36.123 CET [22868] HINT:  Must be superuser to create this extension.
2021-11-28 20:23:36.123 CET [22868] STATEMENT:  --
	-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
	--
	
	CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public
2021-11-28 20:23:46.110 CET [15496] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:23:46.111 CET [22868] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:24:11.107 CET [11824] ERROR:  database "mockdb" already exists
2021-11-28 20:24:11.107 CET [11824] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:24:18.158 CET [1400] ERROR:  unrecognized configuration parameter "default_table_access_method"
2021-11-28 20:24:18.158 CET [1400] STATEMENT:  SET default_table_access_method = heap
2021-11-28 20:24:26.159 CET [1400] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:24:26.159 CET [11824] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:24:51.397 CET [18304] ERROR:  unrecognized configuration parameter "default_table_access_method"
2021-11-28 20:24:51.397 CET [18304] STATEMENT:  SET default_table_access_method = heap
2021-11-28 20:25:19.328 CET [18304] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:25:19.328 CET [27416] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:25:32.707 CET [17640] ERROR:  role "mtcgadmin" does not exist
2021-11-28 20:25:32.707 CET [17640] STATEMENT:  ALTER TABLE public.card_instances OWNER TO mtcgadmin
2021-11-28 20:25:43.095 CET [17640] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:25:43.096 CET [8504] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:26:47.908 CET [30532] ERROR:  relation "info" does not exist at character 15
2021-11-28 20:26:47.908 CET [30532] STATEMENT:  SELECT * FROM info
2021-11-28 20:26:51.357 CET [30532] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:26:51.358 CET [8084] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:27:00.776 CET [21816] ERROR:  relation "info" does not exist at character 15
2021-11-28 20:27:00.776 CET [21816] STATEMENT:  SELECT * FROM info;
2021-11-28 20:28:22.557 CET [21816] ERROR:  syntax error at or near "." at character 46
2021-11-28 20:28:22.557 CET [21816] STATEMENT:  alter role mocking set search_path to mocking.public;
2021-11-28 20:28:39.386 CET [10672] LOG:  received fast shutdown request
2021-11-28 20:28:39.389 CET [10672] LOG:  aborting any active transactions
2021-11-28 20:28:39.394 CET [10672] LOG:  worker process: logical replication launcher (PID 8900) exited with exit code 1
2021-11-28 20:28:39.398 CET [6224] LOG:  shutting down
2021-11-28 20:28:39.470 CET [10672] LOG:  database system is shut down
2021-11-28 20:28:45.064 CET [14596] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:28:45.064 CET [14596] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:28:45.113 CET [2808] LOG:  database system was shut down at 2021-11-28 20:28:39 CET
2021-11-28 20:28:45.244 CET [14596] LOG:  database system is ready to accept connections
2021-11-28 20:29:50.684 CET [4904] ERROR:  syntax error at or near "psql" at character 1
2021-11-28 20:29:50.684 CET [4904] STATEMENT:  psql -U postgres -d mocking
	psql -Upostgres -d mocking
	psql -U postgres -d mocking
	show search_path;
2021-11-28 20:29:54.717 CET [1368] ERROR:  canceling statement due to user request
2021-11-28 20:29:54.719 CET [14596] LOG:  received fast shutdown request
2021-11-28 20:29:54.726 CET [14596] LOG:  aborting any active transactions
2021-11-28 20:29:54.728 CET [14596] LOG:  worker process: logical replication launcher (PID 1368) exited with exit code 1
2021-11-28 20:29:54.732 CET [13536] LOG:  shutting down
2021-11-28 20:29:54.748 CET [14596] LOG:  database system is shut down
2021-11-28 20:29:58.766 CET [27844] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:29:58.766 CET [27844] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:29:58.813 CET [16148] LOG:  database system was shut down at 2021-11-28 20:29:54 CET
2021-11-28 20:29:58.931 CET [27844] LOG:  database system is ready to accept connections
2021-11-28 20:30:11.917 CET [30192] ERROR:  syntax error at or near "psql" at character 1
2021-11-28 20:30:11.917 CET [30192] STATEMENT:  psql -U postgres -d mocking;
2021-11-28 20:30:46.247 CET [30192] ERROR:  syntax error at or near "-" at character 1
2021-11-28 20:30:46.247 CET [30192] STATEMENT:  -U postgres -d mocking;
2021-11-28 20:32:10.977 CET [26280] FATAL:  terminating connection due to administrator command
2021-11-28 20:32:12.978 CET [27536] ERROR:  database "mockdb" already exists
2021-11-28 20:32:12.978 CET [27536] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:32:16.474 CET [5184] ERROR:  relation "card_instances" already exists
2021-11-28 20:32:16.474 CET [5184] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 20:32:29.643 CET [27844] LOG:  worker process: logical replication launcher (PID 7180) was terminated by exception 0xC000013A
2021-11-28 20:32:29.643 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:29.643 CET [27844] LOG:  terminating any other active server processes
2021-11-28 20:32:29.648 CET [27844] LOG:  statistics collector process (PID 26204) was terminated by exception 0xC000013A
2021-11-28 20:32:29.648 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:29.651 CET [27844] LOG:  all server processes terminated; reinitializing
2021-11-28 20:32:29.698 CET [30116] LOG:  database system was interrupted; last known up at 2021-11-28 20:29:58 CET
2021-11-28 20:32:30.038 CET [30116] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:32:30.042 CET [30116] LOG:  redo starts at 0/1713518
2021-11-28 20:32:30.043 CET [30116] LOG:  invalid record length at 0/1717118: wanted 24, got 0
2021-11-28 20:32:30.043 CET [30116] LOG:  redo done at 0/17170D0
2021-11-28 20:32:30.043 CET [30116] LOG:  last completed transaction was at log time 2021-11-28 20:32:21.642245+01
2021-11-28 20:32:30.189 CET [27844] LOG:  database system is ready to accept connections
2021-11-28 20:32:33.153 CET [27844] LOG:  worker process: logical replication launcher (PID 22296) was terminated by exception 0xC000013A
2021-11-28 20:32:33.153 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:33.154 CET [27844] LOG:  terminating any other active server processes
2021-11-28 20:32:33.158 CET [27844] LOG:  statistics collector process (PID 28048) was terminated by exception 0xC000013A
2021-11-28 20:32:33.158 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:33.161 CET [27844] LOG:  all server processes terminated; reinitializing
2021-11-28 20:32:33.204 CET [26368] LOG:  database system was interrupted; last known up at 2021-11-28 20:32:30 CET
2021-11-28 20:32:33.549 CET [26368] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:32:33.551 CET [26368] LOG:  invalid record length at 0/1717188: wanted 24, got 0
2021-11-28 20:32:33.551 CET [26368] LOG:  redo is not required
2021-11-28 20:32:33.673 CET [27844] LOG:  database system is ready to accept connections
2021-11-28 20:32:34.064 CET [27844] LOG:  worker process: logical replication launcher (PID 12384) was terminated by exception 0xC000013A
2021-11-28 20:32:34.064 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:34.064 CET [27844] LOG:  terminating any other active server processes
2021-11-28 20:32:34.068 CET [27844] LOG:  statistics collector process (PID 7100) was terminated by exception 0xC000013A
2021-11-28 20:32:34.068 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:34.070 CET [27844] LOG:  all server processes terminated; reinitializing
2021-11-28 20:32:34.113 CET [24344] LOG:  database system was interrupted; last known up at 2021-11-28 20:32:33 CET
2021-11-28 20:32:34.466 CET [24344] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:32:34.468 CET [24344] LOG:  invalid record length at 0/17171F8: wanted 24, got 0
2021-11-28 20:32:34.469 CET [24344] LOG:  redo is not required
2021-11-28 20:32:34.479 CET [27844] LOG:  startup process (PID 24344) was terminated by exception 0xC000013A
2021-11-28 20:32:34.479 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:34.479 CET [27844] LOG:  aborting startup due to startup process failure
^C2021-11-28 20:47:24.551 CET [15340] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:47:24.551 CET [15340] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:47:25.163 CET [18084] LOG:  database system shutdown was interrupted; last known up at 2021-11-28 20:32:34 CET
2021-11-28 20:47:31.647 CET [15340] LOG:  startup process (PID 18084) was terminated by exception 0xC000013A
2021-11-28 20:47:31.647 CET [15340] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:47:31.647 CET [15340] LOG:  aborting startup due to startup process failure
^C2021-11-28 21:17:32.078 CET [12312] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 21:17:32.078 CET [12312] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 21:17:32.920 CET [29688] LOG:  database system shutdown was interrupted; last known up at 2021-11-28 20:32:34 CET
2021-11-28 21:17:41.451 CET [29688] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 21:17:41.706 CET [29688] LOG:  invalid record length at 0/17171F8: wanted 24, got 0
2021-11-28 21:17:41.706 CET [29688] LOG:  redo is not required
2021-11-28 21:17:42.407 CET [12312] LOG:  database system is ready to accept connections
2021-11-28 21:18:10.537 CET [33148] ERROR:  database "mockdb" already exists
2021-11-28 21:18:10.537 CET [33148] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:18:11.331 CET [23164] ERROR:  relation "card_instances" already exists
2021-11-28 21:18:11.331 CET [23164] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:18:21.024 CET [16228] ERROR:  database "mockdb" already exists
2021-11-28 21:18:21.024 CET [16228] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:18:21.198 CET [4660] ERROR:  relation "card_instances" already exists
2021-11-28 21:18:21.198 CET [4660] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:21:45.879 CET [7408] ERROR:  database "mockdb" already exists
2021-11-28 21:21:45.879 CET [7408] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:21:46.084 CET [27008] ERROR:  relation "card_instances" already exists
2021-11-28 21:21:46.084 CET [27008] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:21:46.606 CET [27008] ERROR:  syntax error at or near "a09" at character 43
2021-11-28 21:21:46.606 CET [27008] STATEMENT:  DELETE FROM users WHERE id=f828efb5-5993-4a09-834c-156811be7cc3
2021-11-28 21:22:10.581 CET [26548] ERROR:  database "mockdb" already exists
2021-11-28 21:22:10.581 CET [26548] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:22:10.976 CET [29156] ERROR:  relation "card_instances" already exists
2021-11-28 21:22:10.976 CET [29156] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:22:42.161 CET [12312] LOG:  server process (PID 1224) was terminated by exception 0xC000013A
2021-11-28 21:22:42.161 CET [12312] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 21:22:42.161 CET [12312] LOG:  terminating any other active server processes
2021-11-28 21:22:42.163 CET [25804] WARNING:  terminating connection because of crash of another server process
2021-11-28 21:22:42.163 CET [25804] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-28 21:22:42.163 CET [25804] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-28 21:22:42.396 CET [12312] LOG:  all server processes terminated; reinitializing
2021-11-28 21:22:42.652 CET [27232] LOG:  database system was interrupted; last known up at 2021-11-28 21:17:42 CET
2021-11-28 21:22:45.076 CET [12312] LOG:  received fast shutdown request
2021-11-28 21:22:47.621 CET [12312] LOG:  startup process (PID 27232) was terminated by exception 0xC000013A
2021-11-28 21:22:47.621 CET [12312] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 21:22:47.621 CET [12312] LOG:  aborting startup due to startup process failure
^C2021-11-28 21:22:54.780 CET [25868] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 21:22:54.780 CET [25868] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 21:22:55.520 CET [23248] LOG:  database system was interrupted; last known up at 2021-11-28 21:17:42 CET
2021-11-28 21:23:03.613 CET [23248] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 21:23:04.078 CET [23248] LOG:  redo starts at 0/1717268
2021-11-28 21:23:04.135 CET [23248] LOG:  invalid record length at 0/171B438: wanted 24, got 0
2021-11-28 21:23:04.136 CET [23248] LOG:  redo done at 0/171B400
2021-11-28 21:23:04.152 CET [23248] LOG:  last completed transaction was at log time 2021-11-28 21:22:10.977864+01
2021-11-28 21:23:05.891 CET [25868] LOG:  database system is ready to accept connections
2021-11-28 21:37:19.511 CET [33368] ERROR:  syntax error at or near "USE" at character 1
2021-11-28 21:37:19.511 CET [33368] STATEMENT:  USE mockdb
	;
2021-11-28 21:38:28.529 CET [15684] ERROR:  relation "users" does not exist at character 15
2021-11-28 21:38:28.529 CET [15684] STATEMENT:  SELECT * FROM users;
2021-11-28 21:38:56.814 CET [15684] ERROR:  column "test" does not exist at character 48
2021-11-28 21:38:56.814 CET [15684] STATEMENT:  DELETE FROM mockdb.public.users WHERE username=test;
2021-11-28 21:39:11.521 CET [12932] ERROR:  canceling statement due to user request
2021-11-28 21:39:11.523 CET [25868] LOG:  received fast shutdown request
2021-11-28 21:39:11.877 CET [25868] LOG:  aborting any active transactions
2021-11-28 21:39:11.877 CET [25868] LOG:  worker process: logical replication launcher (PID 12932) exited with exit code 1
2021-11-28 21:39:11.882 CET [3404] LOG:  shutting down
2021-11-28 21:39:12.791 CET [25868] LOG:  database system is shut down
2021-11-28 21:39:37.402 CET [32396] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 21:39:37.402 CET [32396] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 21:39:38.337 CET [17864] LOG:  database system was shut down at 2021-11-28 21:39:12 CET
2021-11-28 21:39:39.442 CET [32396] LOG:  database system is ready to accept connections
2021-11-28 21:39:51.890 CET [29348] ERROR:  database "mockdb" already exists
2021-11-28 21:39:51.890 CET [29348] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:39:52.423 CET [20188] ERROR:  relation "card_instances" already exists
2021-11-28 21:39:52.423 CET [20188] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:40:34.841 CET [18624] FATAL:  terminating connection due to administrator command
2021-11-28 21:40:34.847 CET [25324] ERROR:  database "mockdb" already exists
2021-11-28 21:40:34.847 CET [25324] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:40:35.026 CET [25980] ERROR:  relation "card_instances" already exists
2021-11-28 21:40:35.026 CET [25980] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:40:47.814 CET [12884] ERROR:  database "mockdb" already exists
2021-11-28 21:40:47.814 CET [12884] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:40:47.925 CET [22408] ERROR:  relation "card_instances" already exists
2021-11-28 21:40:47.925 CET [22408] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:58:23.967 CET [3032] ERROR:  database "mockdb" already exists
2021-11-28 21:58:23.967 CET [3032] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:58:24.177 CET [26864] ERROR:  relation "card_instances" already exists
2021-11-28 21:58:24.177 CET [26864] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:58:24.560 CET [26864] ERROR:  syntax error at or near "c" at character 120
2021-11-28 21:58:24.560 CET [26864] STATEMENT:  INSERT INTO mockdb.public.users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES (27e3399c-9a2a-4415-80b0-43acf36c6947, user1, myhash, 20, 100, 15, false)
2021-11-28 21:58:56.704 CET [17948] ERROR:  database "mockdb" already exists
2021-11-28 21:58:56.704 CET [17948] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:58:56.874 CET [30192] ERROR:  relation "card_instances" already exists
2021-11-28 21:58:56.874 CET [30192] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:58:57.451 CET [30192] ERROR:  column "admin" is of type boolean but expression is of type integer at character 171
2021-11-28 21:58:57.451 CET [30192] HINT:  You will need to rewrite or cast the expression.
2021-11-28 21:58:57.451 CET [30192] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES ('05e9cdb2-88cc-487b-9db6-fcc5b17b704f', 'user1', 'myhash', 20, 100, 15, 0)
2021-11-28 21:59:18.160 CET [26080] ERROR:  database "mockdb" already exists
2021-11-28 21:59:18.160 CET [26080] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:59:18.311 CET [28632] ERROR:  relation "card_instances" already exists
2021-11-28 21:59:18.311 CET [28632] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:59:53.956 CET [5036] FATAL:  terminating connection due to administrator command
2021-11-28 21:59:53.965 CET [26348] ERROR:  database "mockdb" already exists
2021-11-28 21:59:53.965 CET [26348] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:59:54.230 CET [28716] ERROR:  relation "card_instances" already exists
2021-11-28 21:59:54.230 CET [28716] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:59:54.388 CET [28716] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-28 21:59:54.388 CET [28716] DETAIL:  Key (username)=(user1) already exists.
2021-11-28 21:59:54.388 CET [28716] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES ('527a8df6-e1f5-45e0-8107-6fc21ab04d55', 'user1', 'myhash', 20, 100, 15, false)
2021-11-28 22:00:00.592 CET [26348] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:00:00.593 CET [28716] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:00:17.880 CET [11928] FATAL:  terminating connection due to administrator command
2021-11-28 22:00:17.889 CET [5512] ERROR:  database "mockdb" already exists
2021-11-28 22:00:17.889 CET [5512] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:00:18.071 CET [30948] ERROR:  relation "card_instances" already exists
2021-11-28 22:00:18.071 CET [30948] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:00:42.802 CET [30948] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:00:42.802 CET [5512] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:01:49.036 CET [11488] FATAL:  terminating connection due to administrator command
2021-11-28 22:01:49.043 CET [30268] ERROR:  database "mockdb" already exists
2021-11-28 22:01:49.043 CET [30268] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:01:49.356 CET [19820] ERROR:  relation "card_instances" already exists
2021-11-28 22:01:49.356 CET [19820] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:04:59.260 CET [16820] ERROR:  database "mockdb" already exists
2021-11-28 22:04:59.260 CET [16820] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:04:59.432 CET [26712] ERROR:  relation "card_instances" already exists
2021-11-28 22:04:59.432 CET [26712] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:13.757 CET [20840] ERROR:  database "mockdb" already exists
2021-11-28 22:06:13.757 CET [20840] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:13.901 CET [15844] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:13.901 CET [15844] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:39.065 CET [9036] ERROR:  database "mockdb" already exists
2021-11-28 22:06:39.065 CET [9036] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:39.232 CET [8740] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:39.232 CET [8740] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:43.748 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:43.748 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:43.849 CET [10624] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:43.849 CET [10624] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:45.102 CET [10624] FATAL:  terminating connection due to administrator command
2021-11-28 22:06:45.102 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.102 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.205 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.205 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.282 CET [29932] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:45.282 CET [29932] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:45.442 CET [29932] FATAL:  terminating connection due to administrator command
2021-11-28 22:06:45.442 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.442 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.447 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.447 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.509 CET [24748] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:45.509 CET [24748] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:12:36.391 CET [28568] ERROR:  database "mockdb" already exists
2021-11-28 22:12:36.391 CET [28568] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:12:36.559 CET [10196] ERROR:  relation "card_instances" already exists
2021-11-28 22:12:36.559 CET [10196] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:12:37.967 CET [10196] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:12:59.411 CET [4212] ERROR:  database "mockdb" already exists
2021-11-28 22:12:59.411 CET [4212] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:12:59.577 CET [23144] ERROR:  relation "card_instances" already exists
2021-11-28 22:12:59.577 CET [23144] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:13:00.783 CET [23144] FATAL:  terminating connection due to administrator command
2021-11-28 22:13:00.783 CET [4212] ERROR:  database "mockdb" already exists
2021-11-28 22:13:00.783 CET [4212] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:13:00.848 CET [4212] ERROR:  database "mockdb" already exists
2021-11-28 22:13:00.848 CET [4212] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:13:00.939 CET [11636] ERROR:  relation "card_instances" already exists
2021-11-28 22:13:00.939 CET [11636] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:13:01.686 CET [11636] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:15:37.432 CET [16084] ERROR:  database "mockdb" already exists
2021-11-28 22:15:37.432 CET [16084] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:37.594 CET [11008] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:37.594 CET [11008] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:38.629 CET [11008] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:15:43.649 CET [19068] ERROR:  database "mockdb" already exists
2021-11-28 22:15:43.649 CET [19068] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:43.749 CET [15788] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:43.749 CET [15788] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:45.179 CET [15788] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:15:50.324 CET [13484] ERROR:  database "mockdb" already exists
2021-11-28 22:15:50.324 CET [13484] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:50.450 CET [15960] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:50.450 CET [15960] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:50.626 CET [15960] FATAL:  terminating connection due to administrator command
2021-11-28 22:15:50.626 CET [13484] ERROR:  database "mockdb" already exists
2021-11-28 22:15:50.626 CET [13484] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:50.691 CET [13484] ERROR:  database "mockdb" already exists
2021-11-28 22:15:50.691 CET [13484] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:50.765 CET [13320] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:50.765 CET [13320] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:51.281 CET [13320] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:16:36.828 CET [20628] ERROR:  database "mockdb" already exists
2021-11-28 22:16:36.828 CET [20628] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:16:36.996 CET [14652] ERROR:  relation "card_instances" already exists
2021-11-28 22:16:36.996 CET [14652] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:16:38.045 CET [14652] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:17:18.084 CET [13388] ERROR:  database "mockdb" already exists
2021-11-28 22:17:18.084 CET [13388] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:17:18.315 CET [32356] ERROR:  relation "card_instances" already exists
2021-11-28 22:17:18.315 CET [32356] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:17:26.916 CET [32356] FATAL:  terminating connection due to administrator command
2021-11-28 22:17:26.916 CET [13388] ERROR:  database "mockdb" already exists
2021-11-28 22:17:26.916 CET [13388] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:17:30.800 CET [13388] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:17:39.118 CET [21320] ERROR:  database "mockdb" already exists
2021-11-28 22:17:39.118 CET [21320] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:17:39.314 CET [22044] ERROR:  relation "card_instances" already exists
2021-11-28 22:17:39.314 CET [22044] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:17:44.736 CET [22044] FATAL:  terminating connection due to administrator command
2021-11-28 22:17:44.736 CET [21320] ERROR:  database "mockdb" already exists
2021-11-28 22:17:44.736 CET [21320] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:18:06.813 CET [21320] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:18:16.440 CET [20008] ERROR:  database "mockdb" already exists
2021-11-28 22:18:16.440 CET [20008] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:18:16.632 CET [31732] ERROR:  relation "card_instances" already exists
2021-11-28 22:18:16.632 CET [31732] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:18:31.898 CET [31732] FATAL:  terminating connection due to administrator command
2021-11-28 22:18:35.001 CET [20008] ERROR:  database "mockdb" already exists
2021-11-28 22:18:35.001 CET [20008] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:19:07.408 CET [32396] LOG:  server process (PID 20008) was terminated by exception 0xC000013A
2021-11-28 22:19:07.408 CET [32396] DETAIL:  Failed process was running: CREATE DATABASE mockdb
2021-11-28 22:19:07.408 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:19:07.408 CET [32396] LOG:  terminating any other active server processes
2021-11-28 22:19:07.409 CET [29820] WARNING:  terminating connection because of crash of another server process
2021-11-28 22:19:07.409 CET [29820] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-28 22:19:07.409 CET [29820] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-28 22:19:07.612 CET [32396] LOG:  all server processes terminated; reinitializing
2021-11-28 22:19:08.004 CET [22160] LOG:  database system was interrupted; last known up at 2021-11-28 22:14:41 CET
2021-11-28 22:19:16.174 CET [22160] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 22:19:16.745 CET [22160] LOG:  redo starts at 0/172A618
2021-11-28 22:19:16.781 CET [22160] LOG:  invalid record length at 0/1732E50: wanted 24, got 0
2021-11-28 22:19:16.781 CET [22160] LOG:  redo done at 0/1732E18
2021-11-28 22:19:16.783 CET [22160] LOG:  last completed transaction was at log time 2021-11-28 22:18:16.652134+01
2021-11-28 22:19:18.414 CET [32396] LOG:  database system is ready to accept connections
2021-11-28 22:21:55.581 CET [30052] ERROR:  database "mockdb" already exists
2021-11-28 22:21:55.581 CET [30052] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:21:57.248 CET [16108] FATAL:  terminating connection due to administrator command
2021-11-28 22:21:57.248 CET [30052] ERROR:  database "mockdb" already exists
2021-11-28 22:21:57.248 CET [30052] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:21:57.369 CET [30052] ERROR:  database "mockdb" already exists
2021-11-28 22:21:57.369 CET [30052] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:21:58.267 CET [13632] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:22:19.699 CET [30152] ERROR:  database "mockdb" already exists
2021-11-28 22:22:19.699 CET [30152] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:22:20.256 CET [25136] FATAL:  terminating connection due to administrator command
2021-11-28 22:22:20.256 CET [30152] ERROR:  database "mockdb" already exists
2021-11-28 22:22:20.256 CET [30152] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:22:20.364 CET [30152] ERROR:  database "mockdb" already exists
2021-11-28 22:22:20.364 CET [30152] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:22:21.168 CET [10472] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:22:41.405 CET [33468] ERROR:  database "mockdb" already exists
2021-11-28 22:22:41.405 CET [33468] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:23:02.745 CET [29904] ERROR:  database "mockdb" already exists
2021-11-28 22:23:02.745 CET [29904] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:23:38.087 CET [32284] FATAL:  terminating connection due to administrator command
2021-11-28 22:23:41.944 CET [29904] ERROR:  database "mockdb" already exists
2021-11-28 22:23:41.944 CET [29904] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:23:57.391 CET [29904] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:24:08.752 CET [32148] ERROR:  database "mockdb" already exists
2021-11-28 22:24:08.752 CET [32148] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:08.939 CET [32148] ERROR:  database "mockdb" already exists
2021-11-28 22:24:08.939 CET [32148] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:10.228 CET [18544] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:24:36.231 CET [27344] ERROR:  database "mockdb" already exists
2021-11-28 22:24:36.231 CET [27344] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:36.414 CET [27344] ERROR:  database "mockdb" already exists
2021-11-28 22:24:36.414 CET [27344] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:37.625 CET [31280] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:27:24.888 CET [8892] ERROR:  database "mockdb" already exists
2021-11-28 22:27:24.888 CET [8892] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:27:25.080 CET [8892] ERROR:  database "mockdb" already exists
2021-11-28 22:27:25.080 CET [8892] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:27:25.932 CET [21272] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:27:27.362 CET [32396] LOG:  worker process: logical replication launcher (PID 4684) was terminated by exception 0xC000013A
2021-11-28 22:27:27.362 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:27:27.363 CET [32396] LOG:  terminating any other active server processes
2021-11-28 22:27:27.363 CET [1692] WARNING:  terminating connection because of crash of another server process
2021-11-28 22:27:27.363 CET [1692] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-28 22:27:27.363 CET [1692] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-28 22:27:27.366 CET [32396] LOG:  statistics collector process (PID 33476) was terminated by exception 0xC000013A
2021-11-28 22:27:27.366 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:27:27.366 CET [32396] LOG:  all server processes terminated; reinitializing
2021-11-28 22:27:27.551 CET [21584] LOG:  database system was interrupted; last known up at 2021-11-28 22:24:19 CET
2021-11-28 22:27:30.215 CET [32396] LOG:  startup process (PID 21584) was terminated by exception 0xC000013A
2021-11-28 22:27:30.215 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:27:30.215 CET [32396] LOG:  aborting startup due to startup process failure
^C2021-11-29 09:41:07.022 CET [11360] LOG:  listening on IPv6 address "::1", port 15000
2021-11-29 09:41:07.022 CET [11360] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-29 09:41:08.079 CET [6780] LOG:  database system was interrupted; last known up at 2021-11-28 22:24:19 CET
2021-11-29 09:41:16.465 CET [6780] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-29 09:41:16.993 CET [6780] LOG:  redo starts at 0/17368A8
2021-11-29 09:41:17.011 CET [6780] LOG:  invalid record length at 0/1739788: wanted 24, got 0
2021-11-29 09:41:17.011 CET [6780] LOG:  redo done at 0/1739760
2021-11-29 09:41:17.011 CET [6780] LOG:  last completed transaction was at log time 2021-11-28 22:27:25.746287+01
2021-11-29 09:41:18.375 CET [11360] LOG:  database system is ready to accept connections
2021-11-29 09:44:12.931 CET [23464] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 09:44:46.597 CET [30732] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 09:45:18.967 CET [1316] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:40:15.015 CET [17416] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:40:41.989 CET [13972] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:44:17.459 CET [27224] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:47:26.772 CET [17176] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-29 10:47:26.772 CET [17176] DETAIL:  Key (username)=(test) already exists.
2021-11-29 10:47:26.772 CET [17176] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-29 10:47:27.163 CET [17176] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:47:38.012 CET [11360] LOG:  server process (PID 20356) was terminated by exception 0xC000013A
2021-11-29 10:47:38.012 CET [11360] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 10:47:38.012 CET [11360] LOG:  terminating any other active server processes
2021-11-29 10:47:38.016 CET [29736] WARNING:  terminating connection because of crash of another server process
2021-11-29 10:47:38.016 CET [29736] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-29 10:47:38.016 CET [29736] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-29 10:47:38.167 CET [11360] LOG:  all server processes terminated; reinitializing
2021-11-29 10:47:38.345 CET [32100] LOG:  database system was interrupted; last known up at 2021-11-29 10:46:19 CET
2021-11-29 10:47:45.818 CET [32100] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-29 10:47:45.870 CET [32100] LOG:  redo starts at 0/1743320
2021-11-29 10:47:45.874 CET [32100] LOG:  invalid record length at 0/17451C0: wanted 24, got 0
2021-11-29 10:47:45.874 CET [32100] LOG:  redo done at 0/1745188
2021-11-29 10:47:45.874 CET [32100] LOG:  last completed transaction was at log time 2021-11-29 10:47:26.960336+01
2021-11-29 10:47:46.640 CET [11360] LOG:  database system is ready to accept connections
2021-11-29 10:57:12.846 CET [11360] LOG:  worker process: logical replication launcher (PID 27732) was terminated by exception 0xC000013A
2021-11-29 10:57:12.846 CET [11360] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 10:57:12.846 CET [11360] LOG:  terminating any other active server processes
2021-11-29 10:57:12.848 CET [28628] WARNING:  terminating connection because of crash of another server process
2021-11-29 10:57:12.848 CET [28628] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-29 10:57:12.848 CET [28628] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-29 10:57:12.851 CET [11360] LOG:  statistics collector process (PID 26252) was terminated by exception 0xC000013A
2021-11-29 10:57:12.851 CET [11360] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 10:57:12.867 CET [11360] LOG:  all server processes terminated; reinitializing
^C2021-11-29 10:57:15.757 CET [21124] LOG:  database system was interrupted; last known up at 2021-11-29 10:47:46 CET
2021-11-29 13:23:08.470 CET [6380] LOG:  listening on IPv6 address "::1", port 15000
2021-11-29 13:23:08.470 CET [6380] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-29 13:23:09.339 CET [21760] LOG:  database system was interrupted; last known up at 2021-11-29 10:47:46 CET
2021-11-29 13:23:21.222 CET [21708] FATAL:  the database system is starting up
2021-11-29 13:23:21.471 CET [22204] FATAL:  the database system is starting up
2021-11-29 13:23:21.598 CET [22252] FATAL:  the database system is starting up
2021-11-29 13:23:21.710 CET [3620] FATAL:  the database system is starting up
2021-11-29 13:23:21.847 CET [19764] FATAL:  the database system is starting up
2021-11-29 13:23:21.952 CET [21508] FATAL:  the database system is starting up
2021-11-29 13:23:23.517 CET [21760] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-29 13:23:23.834 CET [21760] LOG:  redo starts at 0/1745230
2021-11-29 13:23:23.835 CET [21760] LOG:  invalid record length at 0/1745268: wanted 24, got 0
2021-11-29 13:23:23.835 CET [21760] LOG:  redo done at 0/1745230
2021-11-29 13:23:24.822 CET [6380] LOG:  database system is ready to accept connections
2021-11-29 13:23:40.041 CET [22584] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-29 13:23:40.041 CET [22584] DETAIL:  Key (username)=(test) already exists.
2021-11-29 13:23:40.041 CET [22584] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-29 13:23:40.663 CET [22584] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:30:49.750 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:49.750 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('679922dd-c177-41be-8859-10f091b8ea64', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:49.805 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:49.805 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('c26b9c98-ead5-4385-8516-4c9a8981749b', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:50.442 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:50.442 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('d35efbc6-f88b-4a9c-8529-5a4e202a3909', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:50.443 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:50.443 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('f4186686-9e1b-4176-be09-d2cf58c04ed0', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:50.468 CET [22272] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:32:30.237 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:30.237 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('badec24a-2976-4f33-ae01-8d0a6108d354', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:30.307 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:30.307 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('72211332-f1fe-42ec-9955-76247409ebd8', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:31.906 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:31.906 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('58fe0937-9fb4-425f-86f0-e5f496aab95f', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:31.908 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:31.908 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('620bd62b-f50e-46cc-b178-1929d6aeb6ce', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:31.934 CET [1804] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:33:07.056 CET [21848] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:33:07.056 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('10aea0a1-8793-4ab1-8449-e26eb076469b', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:33:07.109 CET [21848] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:33:07.109 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('8e94669e-6da6-4525-89d5-3c93cc263dd5', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:33:07.677 CET [21848] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:33:07.677 CET [21848] DETAIL:  Key (id)=(89a7669f-1dfa-4098-8f9b-ec80babe8ea7) already exists.
2021-11-29 13:33:07.677 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:33:07.765 CET [21848] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:33:07.765 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('d467ec7f-4a1e-4736-9862-a24039643ff9', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:33:07.818 CET [21848] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:33:51.395 CET [19716] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:33:56.299 CET [1580] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:33:56.299 CET [1580] DETAIL:  Key (id)=(182a89b9-968b-47b3-ace2-c7f356970485) already exists.
2021-11-29 13:33:56.299 CET [1580] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:33:56.655 CET [1580] ERROR:  syntax error at or near "FROM" at character 8
2021-11-29 13:33:56.655 CET [1580] STATEMENT:  UPDATE FROM cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:33:56.814 CET [1580] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:34:30.985 CET [15196] ERROR:  syntax error at or near "FROM" at character 8
2021-11-29 13:34:30.985 CET [15196] STATEMENT:  UPDATE FROM cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:34:38.660 CET [15196] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:35:09.416 CET [18216] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:35:09.416 CET [18216] DETAIL:  Key (id)=(18c3a9f8-d711-4204-8d98-109949f4fc98) already exists.
2021-11-29 13:35:09.416 CET [18216] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:35:09.581 CET [18216] ERROR:  syntax error at or near "=" at character 44
2021-11-29 13:35:09.581 CET [18216] STATEMENT:  UPDATE cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:35:09.739 CET [18216] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:35:27.268 CET [1976] ERROR:  syntax error at or near "=" at character 44
2021-11-29 13:35:27.268 CET [1976] STATEMENT:  UPDATE cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:35:32.290 CET [1976] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:35:41.041 CET [18412] ERROR:  syntax error at or near "=" at character 44
2021-11-29 13:35:41.041 CET [18412] STATEMENT:  UPDATE cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:35:57.939 CET [18412] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:42.602 CET [23576] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:47.747 CET [23608] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:36:47.747 CET [23608] DETAIL:  Key (id)=(d66d8cf6-e272-40bb-be78-578cc29ba968) already exists.
2021-11-29 13:36:47.747 CET [23608] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:36:48.640 CET [18892] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-29 13:36:48.640 CET [18892] DETAIL:  Key (username)=(test) already exists.
2021-11-29 13:36:48.640 CET [18892] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-29 13:36:48.987 CET [18892] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:48.987 CET [23608] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:59.849 CET [6380] LOG:  server process (PID 23144) was terminated by exception 0xC000013A
2021-11-29 13:36:59.849 CET [6380] DETAIL:  Failed process was running: DELETE FROM cards WHERE name='Spell Name'
	;
2021-11-29 13:36:59.849 CET [6380] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 13:36:59.850 CET [6380] LOG:  terminating any other active server processes
2021-11-29 13:36:59.851 CET [21652] WARNING:  terminating connection because of crash of another server process
2021-11-29 13:36:59.851 CET [21652] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-29 13:36:59.851 CET [21652] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-29 13:36:59.976 CET [6380] LOG:  all server processes terminated; reinitializing
2021-11-29 13:37:00.122 CET [23844] LOG:  database system was interrupted; last known up at 2021-11-29 13:33:26 CET
2021-11-29 13:37:06.575 CET [6380] LOG:  startup process (PID 23844) was terminated by exception 0xC000013A
2021-11-29 13:37:06.575 CET [6380] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 13:37:06.575 CET [6380] LOG:  aborting startup due to startup process failure
^C