2021-11-28 20:17:15.953 CET [28424] LOG:  could not bind IPv6 address "::1": Permission denied
2021-11-28 20:17:15.953 CET [28424] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2021-11-28 20:17:15.953 CET [28424] LOG:  could not bind IPv4 address "127.0.0.1": Permission denied
2021-11-28 20:17:15.953 CET [28424] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2021-11-28 20:17:15.953 CET [28424] WARNING:  could not create listen socket for "localhost"
2021-11-28 20:17:15.953 CET [28424] FATAL:  could not create any TCP/IP sockets
2021-11-28 20:17:15.953 CET [28424] LOG:  database system is shut down
2021-11-28 20:18:27.480 CET [33524] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:18:27.480 CET [33524] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:18:27.527 CET [32888] LOG:  database system was shut down at 2021-11-28 20:17:14 CET
2021-11-28 20:18:27.645 CET [33524] LOG:  database system is ready to accept connections
2021-11-28 20:18:30.041 CET [33524] LOG:  server process (PID 22148) was terminated by exception 0xC000013A
2021-11-28 20:18:30.041 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:30.041 CET [33524] LOG:  terminating any other active server processes
2021-11-28 20:18:30.049 CET [33524] LOG:  statistics collector process (PID 12872) was terminated by exception 0xC000013A
2021-11-28 20:18:30.049 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:30.050 CET [33524] LOG:  all server processes terminated; reinitializing
2021-11-28 20:18:30.101 CET [18040] LOG:  database system was interrupted; last known up at 2021-11-28 20:18:27 CET
2021-11-28 20:18:30.358 CET [18040] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:18:30.360 CET [18040] LOG:  invalid record length at 0/1628578: wanted 24, got 0
2021-11-28 20:18:30.360 CET [18040] LOG:  redo is not required
2021-11-28 20:18:30.489 CET [33524] LOG:  database system is ready to accept connections
2021-11-28 20:18:39.122 CET [33524] LOG:  worker process: logical replication launcher (PID 28864) was terminated by exception 0xC000013A
2021-11-28 20:18:39.122 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:39.123 CET [33524] LOG:  terminating any other active server processes
2021-11-28 20:18:39.127 CET [33524] LOG:  statistics collector process (PID 21568) was terminated by exception 0xC000013A
2021-11-28 20:18:39.127 CET [33524] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:18:39.129 CET [33524] LOG:  all server processes terminated; reinitializing
2021-11-28 20:18:39.172 CET [33160] LOG:  database system was interrupted; last known up at 2021-11-28 20:18:30 CET
2021-11-28 20:18:39.425 CET [33160] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:18:39.427 CET [33160] LOG:  invalid record length at 0/16285E8: wanted 24, got 0
2021-11-28 20:18:39.427 CET [33160] LOG:  redo is not required
2021-11-28 20:18:39.549 CET [33524] LOG:  database system is ready to accept connections
2021-11-28 20:18:40.309 CET [26892] ERROR:  canceling statement due to user request
2021-11-28 20:18:40.309 CET [3640] ERROR:  canceling statement due to user request
2021-11-28 20:18:40.311 CET [33524] LOG:  received fast shutdown request
2021-11-28 20:18:40.314 CET [33524] LOG:  aborting any active transactions
2021-11-28 20:18:40.316 CET [33524] LOG:  worker process: logical replication launcher (PID 26892) exited with exit code 1
2021-11-28 20:18:40.331 CET [20180] LOG:  shutting down
2021-11-28 20:18:40.348 CET [33524] LOG:  database system is shut down
2021-11-28 20:18:47.499 CET [10672] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:18:47.499 CET [10672] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:18:47.545 CET [10656] LOG:  database system was shut down at 2021-11-28 20:18:40 CET
2021-11-28 20:18:47.663 CET [10672] LOG:  database system is ready to accept connections
2021-11-28 20:20:48.274 CET [12624] ERROR:  permission denied to create database
2021-11-28 20:20:48.274 CET [12624] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:20:48.315 CET [30588] FATAL:  database "mtcg" does not exist
2021-11-28 20:21:12.397 CET [18588] ERROR:  permission denied to create database
2021-11-28 20:21:12.397 CET [18588] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:21:12.438 CET [5952] FATAL:  database "mockdb" does not exist
2021-11-28 20:21:36.586 CET [31900] ERROR:  permission denied to create database
2021-11-28 20:21:36.586 CET [31900] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:21:40.059 CET [31900] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:23:36.123 CET [22868] ERROR:  permission denied to create extension "uuid-ossp"
2021-11-28 20:23:36.123 CET [22868] HINT:  Must be superuser to create this extension.
2021-11-28 20:23:36.123 CET [22868] STATEMENT:  --
	-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
	--
	
	CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public
2021-11-28 20:23:46.110 CET [15496] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:23:46.111 CET [22868] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:24:11.107 CET [11824] ERROR:  database "mockdb" already exists
2021-11-28 20:24:11.107 CET [11824] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:24:18.158 CET [1400] ERROR:  unrecognized configuration parameter "default_table_access_method"
2021-11-28 20:24:18.158 CET [1400] STATEMENT:  SET default_table_access_method = heap
2021-11-28 20:24:26.159 CET [1400] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:24:26.159 CET [11824] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:24:51.397 CET [18304] ERROR:  unrecognized configuration parameter "default_table_access_method"
2021-11-28 20:24:51.397 CET [18304] STATEMENT:  SET default_table_access_method = heap
2021-11-28 20:25:19.328 CET [18304] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:25:19.328 CET [27416] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:25:32.707 CET [17640] ERROR:  role "mtcgadmin" does not exist
2021-11-28 20:25:32.707 CET [17640] STATEMENT:  ALTER TABLE public.card_instances OWNER TO mtcgadmin
2021-11-28 20:25:43.095 CET [17640] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:25:43.096 CET [8504] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:26:47.908 CET [30532] ERROR:  relation "info" does not exist at character 15
2021-11-28 20:26:47.908 CET [30532] STATEMENT:  SELECT * FROM info
2021-11-28 20:26:51.357 CET [30532] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:26:51.358 CET [8084] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 20:27:00.776 CET [21816] ERROR:  relation "info" does not exist at character 15
2021-11-28 20:27:00.776 CET [21816] STATEMENT:  SELECT * FROM info;
2021-11-28 20:28:22.557 CET [21816] ERROR:  syntax error at or near "." at character 46
2021-11-28 20:28:22.557 CET [21816] STATEMENT:  alter role mocking set search_path to mocking.public;
2021-11-28 20:28:39.386 CET [10672] LOG:  received fast shutdown request
2021-11-28 20:28:39.389 CET [10672] LOG:  aborting any active transactions
2021-11-28 20:28:39.394 CET [10672] LOG:  worker process: logical replication launcher (PID 8900) exited with exit code 1
2021-11-28 20:28:39.398 CET [6224] LOG:  shutting down
2021-11-28 20:28:39.470 CET [10672] LOG:  database system is shut down
2021-11-28 20:28:45.064 CET [14596] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:28:45.064 CET [14596] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:28:45.113 CET [2808] LOG:  database system was shut down at 2021-11-28 20:28:39 CET
2021-11-28 20:28:45.244 CET [14596] LOG:  database system is ready to accept connections
2021-11-28 20:29:50.684 CET [4904] ERROR:  syntax error at or near "psql" at character 1
2021-11-28 20:29:50.684 CET [4904] STATEMENT:  psql -U postgres -d mocking
	psql -Upostgres -d mocking
	psql -U postgres -d mocking
	show search_path;
2021-11-28 20:29:54.717 CET [1368] ERROR:  canceling statement due to user request
2021-11-28 20:29:54.719 CET [14596] LOG:  received fast shutdown request
2021-11-28 20:29:54.726 CET [14596] LOG:  aborting any active transactions
2021-11-28 20:29:54.728 CET [14596] LOG:  worker process: logical replication launcher (PID 1368) exited with exit code 1
2021-11-28 20:29:54.732 CET [13536] LOG:  shutting down
2021-11-28 20:29:54.748 CET [14596] LOG:  database system is shut down
2021-11-28 20:29:58.766 CET [27844] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:29:58.766 CET [27844] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:29:58.813 CET [16148] LOG:  database system was shut down at 2021-11-28 20:29:54 CET
2021-11-28 20:29:58.931 CET [27844] LOG:  database system is ready to accept connections
2021-11-28 20:30:11.917 CET [30192] ERROR:  syntax error at or near "psql" at character 1
2021-11-28 20:30:11.917 CET [30192] STATEMENT:  psql -U postgres -d mocking;
2021-11-28 20:30:46.247 CET [30192] ERROR:  syntax error at or near "-" at character 1
2021-11-28 20:30:46.247 CET [30192] STATEMENT:  -U postgres -d mocking;
2021-11-28 20:32:10.977 CET [26280] FATAL:  terminating connection due to administrator command
2021-11-28 20:32:12.978 CET [27536] ERROR:  database "mockdb" already exists
2021-11-28 20:32:12.978 CET [27536] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 20:32:16.474 CET [5184] ERROR:  relation "card_instances" already exists
2021-11-28 20:32:16.474 CET [5184] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 20:32:29.643 CET [27844] LOG:  worker process: logical replication launcher (PID 7180) was terminated by exception 0xC000013A
2021-11-28 20:32:29.643 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:29.643 CET [27844] LOG:  terminating any other active server processes
2021-11-28 20:32:29.648 CET [27844] LOG:  statistics collector process (PID 26204) was terminated by exception 0xC000013A
2021-11-28 20:32:29.648 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:29.651 CET [27844] LOG:  all server processes terminated; reinitializing
2021-11-28 20:32:29.698 CET [30116] LOG:  database system was interrupted; last known up at 2021-11-28 20:29:58 CET
2021-11-28 20:32:30.038 CET [30116] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:32:30.042 CET [30116] LOG:  redo starts at 0/1713518
2021-11-28 20:32:30.043 CET [30116] LOG:  invalid record length at 0/1717118: wanted 24, got 0
2021-11-28 20:32:30.043 CET [30116] LOG:  redo done at 0/17170D0
2021-11-28 20:32:30.043 CET [30116] LOG:  last completed transaction was at log time 2021-11-28 20:32:21.642245+01
2021-11-28 20:32:30.189 CET [27844] LOG:  database system is ready to accept connections
2021-11-28 20:32:33.153 CET [27844] LOG:  worker process: logical replication launcher (PID 22296) was terminated by exception 0xC000013A
2021-11-28 20:32:33.153 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:33.154 CET [27844] LOG:  terminating any other active server processes
2021-11-28 20:32:33.158 CET [27844] LOG:  statistics collector process (PID 28048) was terminated by exception 0xC000013A
2021-11-28 20:32:33.158 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:33.161 CET [27844] LOG:  all server processes terminated; reinitializing
2021-11-28 20:32:33.204 CET [26368] LOG:  database system was interrupted; last known up at 2021-11-28 20:32:30 CET
2021-11-28 20:32:33.549 CET [26368] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:32:33.551 CET [26368] LOG:  invalid record length at 0/1717188: wanted 24, got 0
2021-11-28 20:32:33.551 CET [26368] LOG:  redo is not required
2021-11-28 20:32:33.673 CET [27844] LOG:  database system is ready to accept connections
2021-11-28 20:32:34.064 CET [27844] LOG:  worker process: logical replication launcher (PID 12384) was terminated by exception 0xC000013A
2021-11-28 20:32:34.064 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:34.064 CET [27844] LOG:  terminating any other active server processes
2021-11-28 20:32:34.068 CET [27844] LOG:  statistics collector process (PID 7100) was terminated by exception 0xC000013A
2021-11-28 20:32:34.068 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:34.070 CET [27844] LOG:  all server processes terminated; reinitializing
2021-11-28 20:32:34.113 CET [24344] LOG:  database system was interrupted; last known up at 2021-11-28 20:32:33 CET
2021-11-28 20:32:34.466 CET [24344] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 20:32:34.468 CET [24344] LOG:  invalid record length at 0/17171F8: wanted 24, got 0
2021-11-28 20:32:34.469 CET [24344] LOG:  redo is not required
2021-11-28 20:32:34.479 CET [27844] LOG:  startup process (PID 24344) was terminated by exception 0xC000013A
2021-11-28 20:32:34.479 CET [27844] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:32:34.479 CET [27844] LOG:  aborting startup due to startup process failure
^C2021-11-28 20:47:24.551 CET [15340] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 20:47:24.551 CET [15340] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 20:47:25.163 CET [18084] LOG:  database system shutdown was interrupted; last known up at 2021-11-28 20:32:34 CET
2021-11-28 20:47:31.647 CET [15340] LOG:  startup process (PID 18084) was terminated by exception 0xC000013A
2021-11-28 20:47:31.647 CET [15340] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 20:47:31.647 CET [15340] LOG:  aborting startup due to startup process failure
^C2021-11-28 21:17:32.078 CET [12312] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 21:17:32.078 CET [12312] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 21:17:32.920 CET [29688] LOG:  database system shutdown was interrupted; last known up at 2021-11-28 20:32:34 CET
2021-11-28 21:17:41.451 CET [29688] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 21:17:41.706 CET [29688] LOG:  invalid record length at 0/17171F8: wanted 24, got 0
2021-11-28 21:17:41.706 CET [29688] LOG:  redo is not required
2021-11-28 21:17:42.407 CET [12312] LOG:  database system is ready to accept connections
2021-11-28 21:18:10.537 CET [33148] ERROR:  database "mockdb" already exists
2021-11-28 21:18:10.537 CET [33148] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:18:11.331 CET [23164] ERROR:  relation "card_instances" already exists
2021-11-28 21:18:11.331 CET [23164] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:18:21.024 CET [16228] ERROR:  database "mockdb" already exists
2021-11-28 21:18:21.024 CET [16228] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:18:21.198 CET [4660] ERROR:  relation "card_instances" already exists
2021-11-28 21:18:21.198 CET [4660] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:21:45.879 CET [7408] ERROR:  database "mockdb" already exists
2021-11-28 21:21:45.879 CET [7408] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:21:46.084 CET [27008] ERROR:  relation "card_instances" already exists
2021-11-28 21:21:46.084 CET [27008] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:21:46.606 CET [27008] ERROR:  syntax error at or near "a09" at character 43
2021-11-28 21:21:46.606 CET [27008] STATEMENT:  DELETE FROM users WHERE id=f828efb5-5993-4a09-834c-156811be7cc3
2021-11-28 21:22:10.581 CET [26548] ERROR:  database "mockdb" already exists
2021-11-28 21:22:10.581 CET [26548] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:22:10.976 CET [29156] ERROR:  relation "card_instances" already exists
2021-11-28 21:22:10.976 CET [29156] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:22:42.161 CET [12312] LOG:  server process (PID 1224) was terminated by exception 0xC000013A
2021-11-28 21:22:42.161 CET [12312] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 21:22:42.161 CET [12312] LOG:  terminating any other active server processes
2021-11-28 21:22:42.163 CET [25804] WARNING:  terminating connection because of crash of another server process
2021-11-28 21:22:42.163 CET [25804] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-28 21:22:42.163 CET [25804] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-28 21:22:42.396 CET [12312] LOG:  all server processes terminated; reinitializing
2021-11-28 21:22:42.652 CET [27232] LOG:  database system was interrupted; last known up at 2021-11-28 21:17:42 CET
2021-11-28 21:22:45.076 CET [12312] LOG:  received fast shutdown request
2021-11-28 21:22:47.621 CET [12312] LOG:  startup process (PID 27232) was terminated by exception 0xC000013A
2021-11-28 21:22:47.621 CET [12312] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 21:22:47.621 CET [12312] LOG:  aborting startup due to startup process failure
^C2021-11-28 21:22:54.780 CET [25868] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 21:22:54.780 CET [25868] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 21:22:55.520 CET [23248] LOG:  database system was interrupted; last known up at 2021-11-28 21:17:42 CET
2021-11-28 21:23:03.613 CET [23248] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 21:23:04.078 CET [23248] LOG:  redo starts at 0/1717268
2021-11-28 21:23:04.135 CET [23248] LOG:  invalid record length at 0/171B438: wanted 24, got 0
2021-11-28 21:23:04.136 CET [23248] LOG:  redo done at 0/171B400
2021-11-28 21:23:04.152 CET [23248] LOG:  last completed transaction was at log time 2021-11-28 21:22:10.977864+01
2021-11-28 21:23:05.891 CET [25868] LOG:  database system is ready to accept connections
2021-11-28 21:37:19.511 CET [33368] ERROR:  syntax error at or near "USE" at character 1
2021-11-28 21:37:19.511 CET [33368] STATEMENT:  USE mockdb
	;
2021-11-28 21:38:28.529 CET [15684] ERROR:  relation "users" does not exist at character 15
2021-11-28 21:38:28.529 CET [15684] STATEMENT:  SELECT * FROM users;
2021-11-28 21:38:56.814 CET [15684] ERROR:  column "test" does not exist at character 48
2021-11-28 21:38:56.814 CET [15684] STATEMENT:  DELETE FROM mockdb.public.users WHERE username=test;
2021-11-28 21:39:11.521 CET [12932] ERROR:  canceling statement due to user request
2021-11-28 21:39:11.523 CET [25868] LOG:  received fast shutdown request
2021-11-28 21:39:11.877 CET [25868] LOG:  aborting any active transactions
2021-11-28 21:39:11.877 CET [25868] LOG:  worker process: logical replication launcher (PID 12932) exited with exit code 1
2021-11-28 21:39:11.882 CET [3404] LOG:  shutting down
2021-11-28 21:39:12.791 CET [25868] LOG:  database system is shut down
2021-11-28 21:39:37.402 CET [32396] LOG:  listening on IPv6 address "::1", port 15000
2021-11-28 21:39:37.402 CET [32396] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-28 21:39:38.337 CET [17864] LOG:  database system was shut down at 2021-11-28 21:39:12 CET
2021-11-28 21:39:39.442 CET [32396] LOG:  database system is ready to accept connections
2021-11-28 21:39:51.890 CET [29348] ERROR:  database "mockdb" already exists
2021-11-28 21:39:51.890 CET [29348] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:39:52.423 CET [20188] ERROR:  relation "card_instances" already exists
2021-11-28 21:39:52.423 CET [20188] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:40:34.841 CET [18624] FATAL:  terminating connection due to administrator command
2021-11-28 21:40:34.847 CET [25324] ERROR:  database "mockdb" already exists
2021-11-28 21:40:34.847 CET [25324] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:40:35.026 CET [25980] ERROR:  relation "card_instances" already exists
2021-11-28 21:40:35.026 CET [25980] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:40:47.814 CET [12884] ERROR:  database "mockdb" already exists
2021-11-28 21:40:47.814 CET [12884] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:40:47.925 CET [22408] ERROR:  relation "card_instances" already exists
2021-11-28 21:40:47.925 CET [22408] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:58:23.967 CET [3032] ERROR:  database "mockdb" already exists
2021-11-28 21:58:23.967 CET [3032] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:58:24.177 CET [26864] ERROR:  relation "card_instances" already exists
2021-11-28 21:58:24.177 CET [26864] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:58:24.560 CET [26864] ERROR:  syntax error at or near "c" at character 120
2021-11-28 21:58:24.560 CET [26864] STATEMENT:  INSERT INTO mockdb.public.users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES (27e3399c-9a2a-4415-80b0-43acf36c6947, user1, myhash, 20, 100, 15, false)
2021-11-28 21:58:56.704 CET [17948] ERROR:  database "mockdb" already exists
2021-11-28 21:58:56.704 CET [17948] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:58:56.874 CET [30192] ERROR:  relation "card_instances" already exists
2021-11-28 21:58:56.874 CET [30192] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:58:57.451 CET [30192] ERROR:  column "admin" is of type boolean but expression is of type integer at character 171
2021-11-28 21:58:57.451 CET [30192] HINT:  You will need to rewrite or cast the expression.
2021-11-28 21:58:57.451 CET [30192] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES ('05e9cdb2-88cc-487b-9db6-fcc5b17b704f', 'user1', 'myhash', 20, 100, 15, 0)
2021-11-28 21:59:18.160 CET [26080] ERROR:  database "mockdb" already exists
2021-11-28 21:59:18.160 CET [26080] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:59:18.311 CET [28632] ERROR:  relation "card_instances" already exists
2021-11-28 21:59:18.311 CET [28632] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:59:53.956 CET [5036] FATAL:  terminating connection due to administrator command
2021-11-28 21:59:53.965 CET [26348] ERROR:  database "mockdb" already exists
2021-11-28 21:59:53.965 CET [26348] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 21:59:54.230 CET [28716] ERROR:  relation "card_instances" already exists
2021-11-28 21:59:54.230 CET [28716] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 21:59:54.388 CET [28716] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-28 21:59:54.388 CET [28716] DETAIL:  Key (username)=(user1) already exists.
2021-11-28 21:59:54.388 CET [28716] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES ('527a8df6-e1f5-45e0-8107-6fc21ab04d55', 'user1', 'myhash', 20, 100, 15, false)
2021-11-28 22:00:00.592 CET [26348] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:00:00.593 CET [28716] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:00:17.880 CET [11928] FATAL:  terminating connection due to administrator command
2021-11-28 22:00:17.889 CET [5512] ERROR:  database "mockdb" already exists
2021-11-28 22:00:17.889 CET [5512] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:00:18.071 CET [30948] ERROR:  relation "card_instances" already exists
2021-11-28 22:00:18.071 CET [30948] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:00:42.802 CET [30948] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:00:42.802 CET [5512] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:01:49.036 CET [11488] FATAL:  terminating connection due to administrator command
2021-11-28 22:01:49.043 CET [30268] ERROR:  database "mockdb" already exists
2021-11-28 22:01:49.043 CET [30268] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:01:49.356 CET [19820] ERROR:  relation "card_instances" already exists
2021-11-28 22:01:49.356 CET [19820] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:04:59.260 CET [16820] ERROR:  database "mockdb" already exists
2021-11-28 22:04:59.260 CET [16820] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:04:59.432 CET [26712] ERROR:  relation "card_instances" already exists
2021-11-28 22:04:59.432 CET [26712] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:13.757 CET [20840] ERROR:  database "mockdb" already exists
2021-11-28 22:06:13.757 CET [20840] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:13.901 CET [15844] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:13.901 CET [15844] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:39.065 CET [9036] ERROR:  database "mockdb" already exists
2021-11-28 22:06:39.065 CET [9036] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:39.232 CET [8740] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:39.232 CET [8740] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:43.748 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:43.748 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:43.849 CET [10624] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:43.849 CET [10624] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:45.102 CET [10624] FATAL:  terminating connection due to administrator command
2021-11-28 22:06:45.102 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.102 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.205 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.205 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.282 CET [29932] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:45.282 CET [29932] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:06:45.442 CET [29932] FATAL:  terminating connection due to administrator command
2021-11-28 22:06:45.442 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.442 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.447 CET [31872] ERROR:  database "mockdb" already exists
2021-11-28 22:06:45.447 CET [31872] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:06:45.509 CET [24748] ERROR:  relation "card_instances" already exists
2021-11-28 22:06:45.509 CET [24748] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:12:36.391 CET [28568] ERROR:  database "mockdb" already exists
2021-11-28 22:12:36.391 CET [28568] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:12:36.559 CET [10196] ERROR:  relation "card_instances" already exists
2021-11-28 22:12:36.559 CET [10196] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:12:37.967 CET [10196] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:12:59.411 CET [4212] ERROR:  database "mockdb" already exists
2021-11-28 22:12:59.411 CET [4212] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:12:59.577 CET [23144] ERROR:  relation "card_instances" already exists
2021-11-28 22:12:59.577 CET [23144] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:13:00.783 CET [23144] FATAL:  terminating connection due to administrator command
2021-11-28 22:13:00.783 CET [4212] ERROR:  database "mockdb" already exists
2021-11-28 22:13:00.783 CET [4212] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:13:00.848 CET [4212] ERROR:  database "mockdb" already exists
2021-11-28 22:13:00.848 CET [4212] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:13:00.939 CET [11636] ERROR:  relation "card_instances" already exists
2021-11-28 22:13:00.939 CET [11636] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:13:01.686 CET [11636] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:15:37.432 CET [16084] ERROR:  database "mockdb" already exists
2021-11-28 22:15:37.432 CET [16084] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:37.594 CET [11008] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:37.594 CET [11008] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:38.629 CET [11008] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:15:43.649 CET [19068] ERROR:  database "mockdb" already exists
2021-11-28 22:15:43.649 CET [19068] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:43.749 CET [15788] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:43.749 CET [15788] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:45.179 CET [15788] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:15:50.324 CET [13484] ERROR:  database "mockdb" already exists
2021-11-28 22:15:50.324 CET [13484] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:50.450 CET [15960] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:50.450 CET [15960] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:50.626 CET [15960] FATAL:  terminating connection due to administrator command
2021-11-28 22:15:50.626 CET [13484] ERROR:  database "mockdb" already exists
2021-11-28 22:15:50.626 CET [13484] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:50.691 CET [13484] ERROR:  database "mockdb" already exists
2021-11-28 22:15:50.691 CET [13484] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:15:50.765 CET [13320] ERROR:  relation "card_instances" already exists
2021-11-28 22:15:50.765 CET [13320] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:15:51.281 CET [13320] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:16:36.828 CET [20628] ERROR:  database "mockdb" already exists
2021-11-28 22:16:36.828 CET [20628] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:16:36.996 CET [14652] ERROR:  relation "card_instances" already exists
2021-11-28 22:16:36.996 CET [14652] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:16:38.045 CET [14652] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:17:18.084 CET [13388] ERROR:  database "mockdb" already exists
2021-11-28 22:17:18.084 CET [13388] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:17:18.315 CET [32356] ERROR:  relation "card_instances" already exists
2021-11-28 22:17:18.315 CET [32356] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:17:26.916 CET [32356] FATAL:  terminating connection due to administrator command
2021-11-28 22:17:26.916 CET [13388] ERROR:  database "mockdb" already exists
2021-11-28 22:17:26.916 CET [13388] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:17:30.800 CET [13388] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:17:39.118 CET [21320] ERROR:  database "mockdb" already exists
2021-11-28 22:17:39.118 CET [21320] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:17:39.314 CET [22044] ERROR:  relation "card_instances" already exists
2021-11-28 22:17:39.314 CET [22044] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:17:44.736 CET [22044] FATAL:  terminating connection due to administrator command
2021-11-28 22:17:44.736 CET [21320] ERROR:  database "mockdb" already exists
2021-11-28 22:17:44.736 CET [21320] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:18:06.813 CET [21320] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:18:16.440 CET [20008] ERROR:  database "mockdb" already exists
2021-11-28 22:18:16.440 CET [20008] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:18:16.632 CET [31732] ERROR:  relation "card_instances" already exists
2021-11-28 22:18:16.632 CET [31732] STATEMENT:  --
	-- Name: card_instances; Type: TABLE; Schema: public; Owner: mocking
	--
	
	CREATE TABLE public.card_instances (
	    id uuid NOT NULL,
	    card_id uuid NOT NULL
	)
2021-11-28 22:18:31.898 CET [31732] FATAL:  terminating connection due to administrator command
2021-11-28 22:18:35.001 CET [20008] ERROR:  database "mockdb" already exists
2021-11-28 22:18:35.001 CET [20008] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:19:07.408 CET [32396] LOG:  server process (PID 20008) was terminated by exception 0xC000013A
2021-11-28 22:19:07.408 CET [32396] DETAIL:  Failed process was running: CREATE DATABASE mockdb
2021-11-28 22:19:07.408 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:19:07.408 CET [32396] LOG:  terminating any other active server processes
2021-11-28 22:19:07.409 CET [29820] WARNING:  terminating connection because of crash of another server process
2021-11-28 22:19:07.409 CET [29820] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-28 22:19:07.409 CET [29820] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-28 22:19:07.612 CET [32396] LOG:  all server processes terminated; reinitializing
2021-11-28 22:19:08.004 CET [22160] LOG:  database system was interrupted; last known up at 2021-11-28 22:14:41 CET
2021-11-28 22:19:16.174 CET [22160] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-28 22:19:16.745 CET [22160] LOG:  redo starts at 0/172A618
2021-11-28 22:19:16.781 CET [22160] LOG:  invalid record length at 0/1732E50: wanted 24, got 0
2021-11-28 22:19:16.781 CET [22160] LOG:  redo done at 0/1732E18
2021-11-28 22:19:16.783 CET [22160] LOG:  last completed transaction was at log time 2021-11-28 22:18:16.652134+01
2021-11-28 22:19:18.414 CET [32396] LOG:  database system is ready to accept connections
2021-11-28 22:21:55.581 CET [30052] ERROR:  database "mockdb" already exists
2021-11-28 22:21:55.581 CET [30052] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:21:57.248 CET [16108] FATAL:  terminating connection due to administrator command
2021-11-28 22:21:57.248 CET [30052] ERROR:  database "mockdb" already exists
2021-11-28 22:21:57.248 CET [30052] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:21:57.369 CET [30052] ERROR:  database "mockdb" already exists
2021-11-28 22:21:57.369 CET [30052] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:21:58.267 CET [13632] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:22:19.699 CET [30152] ERROR:  database "mockdb" already exists
2021-11-28 22:22:19.699 CET [30152] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:22:20.256 CET [25136] FATAL:  terminating connection due to administrator command
2021-11-28 22:22:20.256 CET [30152] ERROR:  database "mockdb" already exists
2021-11-28 22:22:20.256 CET [30152] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:22:20.364 CET [30152] ERROR:  database "mockdb" already exists
2021-11-28 22:22:20.364 CET [30152] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:22:21.168 CET [10472] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:22:41.405 CET [33468] ERROR:  database "mockdb" already exists
2021-11-28 22:22:41.405 CET [33468] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:23:02.745 CET [29904] ERROR:  database "mockdb" already exists
2021-11-28 22:23:02.745 CET [29904] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:23:38.087 CET [32284] FATAL:  terminating connection due to administrator command
2021-11-28 22:23:41.944 CET [29904] ERROR:  database "mockdb" already exists
2021-11-28 22:23:41.944 CET [29904] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:23:57.391 CET [29904] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:24:08.752 CET [32148] ERROR:  database "mockdb" already exists
2021-11-28 22:24:08.752 CET [32148] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:08.939 CET [32148] ERROR:  database "mockdb" already exists
2021-11-28 22:24:08.939 CET [32148] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:10.228 CET [18544] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:24:36.231 CET [27344] ERROR:  database "mockdb" already exists
2021-11-28 22:24:36.231 CET [27344] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:36.414 CET [27344] ERROR:  database "mockdb" already exists
2021-11-28 22:24:36.414 CET [27344] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:24:37.625 CET [31280] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:27:24.888 CET [8892] ERROR:  database "mockdb" already exists
2021-11-28 22:27:24.888 CET [8892] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:27:25.080 CET [8892] ERROR:  database "mockdb" already exists
2021-11-28 22:27:25.080 CET [8892] STATEMENT:  CREATE DATABASE mockdb
2021-11-28 22:27:25.932 CET [21272] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-28 22:27:27.362 CET [32396] LOG:  worker process: logical replication launcher (PID 4684) was terminated by exception 0xC000013A
2021-11-28 22:27:27.362 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:27:27.363 CET [32396] LOG:  terminating any other active server processes
2021-11-28 22:27:27.363 CET [1692] WARNING:  terminating connection because of crash of another server process
2021-11-28 22:27:27.363 CET [1692] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-28 22:27:27.363 CET [1692] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-28 22:27:27.366 CET [32396] LOG:  statistics collector process (PID 33476) was terminated by exception 0xC000013A
2021-11-28 22:27:27.366 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:27:27.366 CET [32396] LOG:  all server processes terminated; reinitializing
2021-11-28 22:27:27.551 CET [21584] LOG:  database system was interrupted; last known up at 2021-11-28 22:24:19 CET
2021-11-28 22:27:30.215 CET [32396] LOG:  startup process (PID 21584) was terminated by exception 0xC000013A
2021-11-28 22:27:30.215 CET [32396] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-28 22:27:30.215 CET [32396] LOG:  aborting startup due to startup process failure
^C2021-11-29 09:41:07.022 CET [11360] LOG:  listening on IPv6 address "::1", port 15000
2021-11-29 09:41:07.022 CET [11360] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-29 09:41:08.079 CET [6780] LOG:  database system was interrupted; last known up at 2021-11-28 22:24:19 CET
2021-11-29 09:41:16.465 CET [6780] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-29 09:41:16.993 CET [6780] LOG:  redo starts at 0/17368A8
2021-11-29 09:41:17.011 CET [6780] LOG:  invalid record length at 0/1739788: wanted 24, got 0
2021-11-29 09:41:17.011 CET [6780] LOG:  redo done at 0/1739760
2021-11-29 09:41:17.011 CET [6780] LOG:  last completed transaction was at log time 2021-11-28 22:27:25.746287+01
2021-11-29 09:41:18.375 CET [11360] LOG:  database system is ready to accept connections
2021-11-29 09:44:12.931 CET [23464] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 09:44:46.597 CET [30732] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 09:45:18.967 CET [1316] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:40:15.015 CET [17416] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:40:41.989 CET [13972] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:44:17.459 CET [27224] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:47:26.772 CET [17176] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-29 10:47:26.772 CET [17176] DETAIL:  Key (username)=(test) already exists.
2021-11-29 10:47:26.772 CET [17176] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-29 10:47:27.163 CET [17176] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 10:47:38.012 CET [11360] LOG:  server process (PID 20356) was terminated by exception 0xC000013A
2021-11-29 10:47:38.012 CET [11360] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 10:47:38.012 CET [11360] LOG:  terminating any other active server processes
2021-11-29 10:47:38.016 CET [29736] WARNING:  terminating connection because of crash of another server process
2021-11-29 10:47:38.016 CET [29736] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-29 10:47:38.016 CET [29736] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-29 10:47:38.167 CET [11360] LOG:  all server processes terminated; reinitializing
2021-11-29 10:47:38.345 CET [32100] LOG:  database system was interrupted; last known up at 2021-11-29 10:46:19 CET
2021-11-29 10:47:45.818 CET [32100] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-29 10:47:45.870 CET [32100] LOG:  redo starts at 0/1743320
2021-11-29 10:47:45.874 CET [32100] LOG:  invalid record length at 0/17451C0: wanted 24, got 0
2021-11-29 10:47:45.874 CET [32100] LOG:  redo done at 0/1745188
2021-11-29 10:47:45.874 CET [32100] LOG:  last completed transaction was at log time 2021-11-29 10:47:26.960336+01
2021-11-29 10:47:46.640 CET [11360] LOG:  database system is ready to accept connections
2021-11-29 10:57:12.846 CET [11360] LOG:  worker process: logical replication launcher (PID 27732) was terminated by exception 0xC000013A
2021-11-29 10:57:12.846 CET [11360] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 10:57:12.846 CET [11360] LOG:  terminating any other active server processes
2021-11-29 10:57:12.848 CET [28628] WARNING:  terminating connection because of crash of another server process
2021-11-29 10:57:12.848 CET [28628] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-29 10:57:12.848 CET [28628] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-29 10:57:12.851 CET [11360] LOG:  statistics collector process (PID 26252) was terminated by exception 0xC000013A
2021-11-29 10:57:12.851 CET [11360] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 10:57:12.867 CET [11360] LOG:  all server processes terminated; reinitializing
^C2021-11-29 10:57:15.757 CET [21124] LOG:  database system was interrupted; last known up at 2021-11-29 10:47:46 CET
2021-11-29 13:23:08.470 CET [6380] LOG:  listening on IPv6 address "::1", port 15000
2021-11-29 13:23:08.470 CET [6380] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-29 13:23:09.339 CET [21760] LOG:  database system was interrupted; last known up at 2021-11-29 10:47:46 CET
2021-11-29 13:23:21.222 CET [21708] FATAL:  the database system is starting up
2021-11-29 13:23:21.471 CET [22204] FATAL:  the database system is starting up
2021-11-29 13:23:21.598 CET [22252] FATAL:  the database system is starting up
2021-11-29 13:23:21.710 CET [3620] FATAL:  the database system is starting up
2021-11-29 13:23:21.847 CET [19764] FATAL:  the database system is starting up
2021-11-29 13:23:21.952 CET [21508] FATAL:  the database system is starting up
2021-11-29 13:23:23.517 CET [21760] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-29 13:23:23.834 CET [21760] LOG:  redo starts at 0/1745230
2021-11-29 13:23:23.835 CET [21760] LOG:  invalid record length at 0/1745268: wanted 24, got 0
2021-11-29 13:23:23.835 CET [21760] LOG:  redo done at 0/1745230
2021-11-29 13:23:24.822 CET [6380] LOG:  database system is ready to accept connections
2021-11-29 13:23:40.041 CET [22584] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-29 13:23:40.041 CET [22584] DETAIL:  Key (username)=(test) already exists.
2021-11-29 13:23:40.041 CET [22584] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-29 13:23:40.663 CET [22584] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:30:49.750 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:49.750 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('679922dd-c177-41be-8859-10f091b8ea64', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:49.805 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:49.805 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('c26b9c98-ead5-4385-8516-4c9a8981749b', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:50.442 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:50.442 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('d35efbc6-f88b-4a9c-8529-5a4e202a3909', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:50.443 CET [22272] ERROR:  column "card_type" of relation "cards" does not exist at character 51
2021-11-29 13:30:50.443 CET [22272] STATEMENT:  INSERT INTO cards (id, name, description, damage, card_type, element, race, rarity) 
	                VALUES ('f4186686-9e1b-4176-be09-d2cf58c04ed0', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:30:50.468 CET [22272] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:32:30.237 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:30.237 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('badec24a-2976-4f33-ae01-8d0a6108d354', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:30.307 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:30.307 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('72211332-f1fe-42ec-9955-76247409ebd8', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:31.906 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:31.906 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('58fe0937-9fb4-425f-86f0-e5f496aab95f', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:31.908 CET [1804] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:32:31.908 CET [1804] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('620bd62b-f50e-46cc-b178-1929d6aeb6ce', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:32:31.934 CET [1804] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:33:07.056 CET [21848] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:33:07.056 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('10aea0a1-8793-4ab1-8449-e26eb076469b', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:33:07.109 CET [21848] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:33:07.109 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('8e94669e-6da6-4525-89d5-3c93cc263dd5', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:33:07.677 CET [21848] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:33:07.677 CET [21848] DETAIL:  Key (id)=(89a7669f-1dfa-4098-8f9b-ec80babe8ea7) already exists.
2021-11-29 13:33:07.677 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:33:07.765 CET [21848] ERROR:  column "spell" does not exist at character 198
2021-11-29 13:33:07.765 CET [21848] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                VALUES ('d467ec7f-4a1e-4736-9862-a24039643ff9', 'Spell Name', 'Description!!!', 5,
	                Spell, Fire, None, Rare)
2021-11-29 13:33:07.818 CET [21848] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:33:51.395 CET [19716] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:33:56.299 CET [1580] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:33:56.299 CET [1580] DETAIL:  Key (id)=(182a89b9-968b-47b3-ace2-c7f356970485) already exists.
2021-11-29 13:33:56.299 CET [1580] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:33:56.655 CET [1580] ERROR:  syntax error at or near "FROM" at character 8
2021-11-29 13:33:56.655 CET [1580] STATEMENT:  UPDATE FROM cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:33:56.814 CET [1580] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:34:30.985 CET [15196] ERROR:  syntax error at or near "FROM" at character 8
2021-11-29 13:34:30.985 CET [15196] STATEMENT:  UPDATE FROM cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:34:38.660 CET [15196] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:35:09.416 CET [18216] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:35:09.416 CET [18216] DETAIL:  Key (id)=(18c3a9f8-d711-4204-8d98-109949f4fc98) already exists.
2021-11-29 13:35:09.416 CET [18216] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:35:09.581 CET [18216] ERROR:  syntax error at or near "=" at character 44
2021-11-29 13:35:09.581 CET [18216] STATEMENT:  UPDATE cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:35:09.739 CET [18216] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:35:27.268 CET [1976] ERROR:  syntax error at or near "=" at character 44
2021-11-29 13:35:27.268 CET [1976] STATEMENT:  UPDATE cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:35:32.290 CET [1976] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:35:41.041 CET [18412] ERROR:  syntax error at or near "=" at character 44
2021-11-29 13:35:41.041 CET [18412] STATEMENT:  UPDATE cards 
	                    SET(name=$1, description=$2, type=$3, damage=$4, 
	                    element=$5, rarity=$6, race=$7)
	                    WHERE id=$8
2021-11-29 13:35:57.939 CET [18412] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:42.602 CET [23576] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:47.747 CET [23608] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-29 13:36:47.747 CET [23608] DETAIL:  Key (id)=(d66d8cf6-e272-40bb-be78-578cc29ba968) already exists.
2021-11-29 13:36:47.747 CET [23608] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-29 13:36:48.640 CET [18892] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-29 13:36:48.640 CET [18892] DETAIL:  Key (username)=(test) already exists.
2021-11-29 13:36:48.640 CET [18892] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-29 13:36:48.987 CET [18892] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:48.987 CET [23608] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 13:36:59.849 CET [6380] LOG:  server process (PID 23144) was terminated by exception 0xC000013A
2021-11-29 13:36:59.849 CET [6380] DETAIL:  Failed process was running: DELETE FROM cards WHERE name='Spell Name'
	;
2021-11-29 13:36:59.849 CET [6380] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 13:36:59.850 CET [6380] LOG:  terminating any other active server processes
2021-11-29 13:36:59.851 CET [21652] WARNING:  terminating connection because of crash of another server process
2021-11-29 13:36:59.851 CET [21652] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-29 13:36:59.851 CET [21652] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-29 13:36:59.976 CET [6380] LOG:  all server processes terminated; reinitializing
2021-11-29 13:37:00.122 CET [23844] LOG:  database system was interrupted; last known up at 2021-11-29 13:33:26 CET
2021-11-29 13:37:06.575 CET [6380] LOG:  startup process (PID 23844) was terminated by exception 0xC000013A
2021-11-29 13:37:06.575 CET [6380] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 13:37:06.575 CET [6380] LOG:  aborting startup due to startup process failure
^C2021-11-29 22:03:35.804 CET [10740] LOG:  listening on IPv6 address "::1", port 15000
2021-11-29 22:03:35.805 CET [10740] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-29 22:03:36.620 CET [3616] LOG:  database system was interrupted; last known up at 2021-11-29 13:33:26 CET
2021-11-29 22:03:46.338 CET [3616] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-29 22:03:46.729 CET [3616] LOG:  redo starts at 0/1747C00
2021-11-29 22:03:46.754 CET [3616] LOG:  invalid record length at 0/174C220: wanted 24, got 0
2021-11-29 22:03:46.754 CET [3616] LOG:  redo done at 0/174C1E8
2021-11-29 22:03:46.754 CET [3616] LOG:  last completed transaction was at log time 2021-11-29 13:36:48.778099+01
2021-11-29 22:03:48.187 CET [10740] LOG:  database system is ready to accept connections
2021-11-29 22:05:02.001 CET [21544] ERROR:  insert or update on table "card_instances" violates foreign key constraint "fk_card_instances_card_id"
2021-11-29 22:05:02.001 CET [21544] DETAIL:  Key (card_id)=(cc858c03-c7d7-4d9e-a0db-4c034b4072a2) is not present in table "cards".
2021-11-29 22:05:02.001 CET [21544] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-29 22:05:02.608 CET [21544] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:06:46.721 CET [20424] FATAL:  role "production" does not exist
2021-11-29 22:07:19.520 CET [996] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:07:51.192 CET [172] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:08:18.532 CET [20220] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:09:09.816 CET [11164] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:10:25.997 CET [14948] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:11:01.664 CET [14152] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:11:26.019 CET [15720] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-29 22:12:05.409 CET [10740] LOG:  server process (PID 23076) was terminated by exception 0xC000013A
2021-11-29 22:12:05.409 CET [10740] DETAIL:  Failed process was running: SELECT * FROM cards;
2021-11-29 22:12:05.409 CET [10740] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 22:12:05.409 CET [10740] LOG:  terminating any other active server processes
2021-11-29 22:12:05.410 CET [19396] WARNING:  terminating connection because of crash of another server process
2021-11-29 22:12:05.410 CET [19396] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-29 22:12:05.410 CET [19396] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-29 22:12:06.601 CET [10740] LOG:  all server processes terminated; reinitializing
2021-11-29 22:12:07.135 CET [17956] LOG:  database system was interrupted; last known up at 2021-11-29 22:08:50 CET
2021-11-29 22:12:09.055 CET [10740] LOG:  startup process (PID 17956) was terminated by exception 0xC000013A
2021-11-29 22:12:09.055 CET [10740] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-29 22:12:09.055 CET [10740] LOG:  aborting startup due to startup process failure
^C2021-11-30 11:46:42.060 CET [24968] LOG:  listening on IPv6 address "::1", port 15000
2021-11-30 11:46:42.060 CET [24968] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-11-30 11:46:42.794 CET [7088] LOG:  database system was interrupted; last known up at 2021-11-29 22:08:50 CET
2021-11-30 11:46:50.355 CET [7088] LOG:  database system was not properly shut down; automatic recovery in progress
2021-11-30 11:46:51.494 CET [7088] LOG:  redo starts at 0/174DC10
2021-11-30 11:46:51.507 CET [7088] LOG:  invalid record length at 0/174FB38: wanted 24, got 0
2021-11-30 11:46:51.507 CET [7088] LOG:  redo done at 0/174FB00
2021-11-30 11:46:51.507 CET [7088] LOG:  last completed transaction was at log time 2021-11-29 22:11:25.900704+01
2021-11-30 11:46:52.825 CET [24968] LOG:  database system is ready to accept connections
2021-11-30 11:58:52.085 CET [28120] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 11:59:15.769 CET [14480] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 11:59:15.769 CET [14480] DETAIL:  Key (id)=(0b79b94c-9521-4834-a412-6418e7365af6) already exists.
2021-11-30 11:59:15.769 CET [14480] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 11:59:16.000 CET [14480] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 11:59:32.536 CET [28612] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 11:59:32.536 CET [28612] DETAIL:  Key (id)=(8293caa0-5f46-4274-ade3-d2fe92f4afd2) already exists.
2021-11-30 11:59:32.536 CET [28612] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 11:59:32.647 CET [28612] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:07:52.336 CET [10636] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 12:07:52.336 CET [10636] DETAIL:  Key (id)=(18cf8aba-eea8-45b7-a213-3dd1fcb690e8) already exists.
2021-11-30 12:07:52.336 CET [10636] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 12:07:52.842 CET [9760] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-30 12:07:52.842 CET [9760] DETAIL:  Key (id)=(9366339a-a59f-43d5-b43a-051e536f50cf) already exists.
2021-11-30 12:07:52.842 CET [9760] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-30 12:07:53.544 CET [18528] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-30 12:07:53.544 CET [18528] DETAIL:  Key (username)=(test) already exists.
2021-11-30 12:07:53.544 CET [18528] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-30 12:07:54.037 CET [18528] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:07:54.037 CET [10636] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:07:54.037 CET [9760] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:08:58.845 CET [28344] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 12:08:58.845 CET [28344] DETAIL:  Key (id)=(e0269aee-6d56-4fbe-89b9-904a4ca23be8) already exists.
2021-11-30 12:08:58.845 CET [28344] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 12:08:59.390 CET [28088] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-30 12:08:59.390 CET [28088] DETAIL:  Key (id)=(69c7f220-11b3-4304-90e3-4c8a43a3926a) already exists.
2021-11-30 12:08:59.390 CET [28088] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-30 12:09:00.027 CET [23784] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-30 12:09:00.027 CET [23784] DETAIL:  Key (username)=(test) already exists.
2021-11-30 12:09:00.027 CET [23784] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-30 12:09:00.398 CET [28344] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:09:00.398 CET [28088] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:09:00.398 CET [23784] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:12:53.121 CET [1344] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:13:44.851 CET [28108] ERROR:  syntax error at or near "VALUES" at character 37
2021-11-30 12:13:44.851 CET [28108] STATEMENT:  UPDATE card_instances SET (card_id) VALUES ($1) WHERE id=$2
2021-11-30 12:13:44.928 CET [28108] ERROR:  syntax error at or near "fb74f1" at character 76
2021-11-30 12:13:44.928 CET [28108] STATEMENT:  DELETE FROM cards WHERE id='1f2ae169-f050-4d01-ac0c-6272ff10468a' AND id=23fb74f1-0501-466d-965e-b9c7a654b6f3
2021-11-30 12:13:44.995 CET [28108] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:14:19.974 CET [18380] ERROR:  syntax error at or near "1" at character 24
2021-11-30 12:14:19.974 CET [18380] STATEMENT:  DELETE FROM cards WHRE 1=1;
2021-11-30 12:14:38.712 CET [11328] ERROR:  syntax error at or near "VALUES" at character 37
2021-11-30 12:14:38.712 CET [11328] STATEMENT:  UPDATE card_instances SET (card_id) VALUES ($1) WHERE id=$2
2021-11-30 12:14:38.881 CET [11328] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:16:10.668 CET [25796] ERROR:  syntax error at or near "VALUES" at character 37
2021-11-30 12:16:10.668 CET [25796] STATEMENT:  UPDATE card_instances SET (card_id) VALUES ($1) WHERE id=$2
2021-11-30 12:16:10.803 CET [25796] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:16:30.480 CET [27988] ERROR:  syntax error at or near "VALUES" at character 37
2021-11-30 12:16:30.480 CET [27988] STATEMENT:  UPDATE card_instances SET (card_id) VALUES ($1) WHERE id=$2
2021-11-30 12:16:30.648 CET [27988] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:18:06.737 CET [13096] ERROR:  syntax error at or near "VALUES" at character 37
2021-11-30 12:18:06.737 CET [13096] STATEMENT:  UPDATE card_instances SET (card_id) VALUES ($1) WHERE id=$2
2021-11-30 12:18:18.714 CET [13096] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:18:55.888 CET [10624] ERROR:  syntax error at or near "VALUES" at character 37
2021-11-30 12:18:55.888 CET [10624] STATEMENT:  UPDATE card_instances SET (card_id) VALUES ($1) WHERE id=$2
2021-11-30 12:18:56.039 CET [10624] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:19:38.655 CET [2012] ERROR:  syntax error at or near "VALUES" at character 37
2021-11-30 12:19:38.655 CET [2012] STATEMENT:  UPDATE card_instances SET (card_id) VALUES ($1) WHERE id=$2
2021-11-30 12:19:51.127 CET [2012] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:20:15.475 CET [20124] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:23:27.658 CET [2936] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:24:43.442 CET [19976] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:29:25.032 CET [1048] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 12:29:25.032 CET [1048] DETAIL:  Key (id)=(035d8c1e-32c9-4cd9-bd9c-c4f1d3889f76) already exists.
2021-11-30 12:29:25.032 CET [1048] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 12:29:25.271 CET [1048] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:31:01.288 CET [18148] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 12:31:01.288 CET [18148] DETAIL:  Key (id)=(e5a9dfbb-2e30-42cd-8fa9-38706e528966) already exists.
2021-11-30 12:31:01.288 CET [18148] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 12:31:01.476 CET [18148] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 12:31:01.476 CET [18148] DETAIL:  Key (id)=(67c98d98-6c47-44cc-a19d-ea25a0262772) already exists.
2021-11-30 12:31:01.476 CET [18148] STATEMENT:  INSERT INTO card_instances (id, card_id) 
	                VALUES ('67c98d98-6c47-44cc-a19d-ea25a0262772', '371def50-7945-4455-8410-6db2875f79e9')
2021-11-30 12:31:01.795 CET [18148] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:31:16.667 CET [17428] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:31:45.867 CET [8448] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:32:07.123 CET [12084] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:32:43.806 CET [18796] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:33:39.751 CET [19536] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:34:01.477 CET [28900] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 12:34:01.477 CET [28900] DETAIL:  Key (id)=(76bd59d9-939b-4e21-a542-0ccbc66eae07) already exists.
2021-11-30 12:34:01.477 CET [28900] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 12:34:01.607 CET [28900] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:34:09.802 CET [3832] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-11-30 12:34:09.802 CET [3832] DETAIL:  Key (id)=(310f7e01-01e9-4402-9a67-b395843ca509) already exists.
2021-11-30 12:34:09.802 CET [3832] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-11-30 12:34:10.554 CET [15264] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-11-30 12:34:10.554 CET [15264] DETAIL:  Key (id)=(09bcc163-6407-44d9-a845-cd6582728228) already exists.
2021-11-30 12:34:10.554 CET [15264] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-11-30 12:34:11.436 CET [14060] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-11-30 12:34:11.436 CET [14060] DETAIL:  Key (username)=(test) already exists.
2021-11-30 12:34:11.436 CET [14060] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, admin, played_games) VALUES ($1, $2, $3, $4, $5, false, $6)
2021-11-30 12:34:11.776 CET [15264] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:34:11.776 CET [3832] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:34:11.776 CET [14060] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-11-30 12:34:25.862 CET [24968] LOG:  server process (PID 18380) was terminated by exception 0xC000013A
2021-11-30 12:34:25.862 CET [24968] DETAIL:  Failed process was running: DELETE FROM card_instances;
2021-11-30 12:34:25.862 CET [24968] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-30 12:34:25.862 CET [24968] LOG:  terminating any other active server processes
2021-11-30 12:34:25.864 CET [27084] WARNING:  terminating connection because of crash of another server process
2021-11-30 12:34:25.864 CET [27084] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-11-30 12:34:25.864 CET [27084] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-11-30 12:34:25.882 CET [24968] LOG:  statistics collector process (PID 25520) was terminated by exception 0xC000013A
2021-11-30 12:34:25.882 CET [24968] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-30 12:34:25.882 CET [24968] LOG:  all server processes terminated; reinitializing
2021-11-30 12:34:26.058 CET [27644] LOG:  database system was interrupted; last known up at 2021-11-30 12:31:55 CET
2021-11-30 12:34:30.343 CET [24968] LOG:  startup process (PID 27644) was terminated by exception 0xC000013A
2021-11-30 12:34:30.343 CET [24968] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-11-30 12:34:30.343 CET [24968] LOG:  aborting startup due to startup process failure
^C2021-12-02 23:04:01.399 CET [24820] LOG:  listening on IPv6 address "::1", port 15000
2021-12-02 23:04:01.399 CET [24820] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-02 23:04:02.095 CET [19176] LOG:  database system was interrupted; last known up at 2021-11-30 12:31:55 CET
2021-12-02 23:04:10.366 CET [19176] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-02 23:04:11.737 CET [19176] LOG:  redo starts at 0/1769E60
2021-12-02 23:04:12.157 CET [19176] LOG:  invalid record length at 0/1778108: wanted 24, got 0
2021-12-02 23:04:12.157 CET [19176] LOG:  redo done at 0/17780D0
2021-12-02 23:04:12.157 CET [19176] LOG:  last completed transaction was at log time 2021-11-30 12:34:11.564355+01
2021-12-02 23:04:14.699 CET [24820] LOG:  database system is ready to accept connections
2021-12-02 23:04:30.587 CET [23112] ERROR:  relation "deck" does not exist at character 15
2021-12-02 23:04:30.587 CET [23112] STATEMENT:  SELECT * FROM deck WHERE id='c5579f87-00e1-4ca9-9b14-51731d0f9668'
2021-12-02 23:04:30.812 CET [23112] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:06:02.986 CET [25520] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:07:04.559 CET [18352] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:11:35.759 CET [22960] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:13:24.240 CET [25804] ERROR:  insert or update on table "user_decks" violates foreign key constraint "fk_user_deck_user_id"
2021-12-02 23:13:24.240 CET [25804] DETAIL:  Key (user_id)=(483e9679-059a-4644-a0d5-62176752060d) is not present in table "users".
2021-12-02 23:13:24.240 CET [25804] STATEMENT:  INSERT INTO user_decks (deck_id, user_id, main_deck) VALUES ($1, $2, $3)
2021-12-02 23:14:17.047 CET [25804] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:16:06.699 CET [28792] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:17:01.925 CET [15480] ERROR:  syntax error at or near "=" at character 47
2021-12-02 23:17:01.925 CET [15480] STATEMENT:  SELECT * FROM decks, user_decks WHERE id = id ='19185f62-3a54-4b93-9c52-6a8d7cfa459e' AND deck_id = id
2021-12-02 23:17:06.489 CET [15480] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:17:44.954 CET [13720] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:18:43.324 CET [12040] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:19:11.197 CET [14952] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-02 23:19:11.197 CET [14952] DETAIL:  Key (username)=(rasebdon) already exists.
2021-12-02 23:19:11.197 CET [14952] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES ('4efd5bdb-520a-47dd-84af-8c010b45f292', 'rasebdon', 'hash', 20, 5, 25, False)
2021-12-02 23:19:18.294 CET [14952] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:19:25.017 CET [23276] ERROR:  syntax error at or near "*" at character 8
2021-12-02 23:19:25.017 CET [23276] STATEMENT:  DELETE * FROM users;
2021-12-02 23:20:33.095 CET [10592] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:21:56.612 CET [9264] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:22:00.277 CET [23276] ERROR:  syntax error at or near "#" at character 1
2021-12-02 23:22:00.277 CET [23276] STATEMENT:  #
	DELETE FROM users;
2021-12-02 23:22:02.861 CET [23276] ERROR:  syntax error at or near "#" at character 1
2021-12-02 23:22:02.861 CET [23276] STATEMENT:  #
	DELETE FROM users;
2021-12-02 23:23:35.436 CET [21096] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:23:50.847 CET [23820] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-02 23:24:07.225 CET [24820] LOG:  server process (PID 23276) was terminated by exception 0xC000013A
2021-12-02 23:24:07.225 CET [24820] DETAIL:  Failed process was running: SELECT * FROM cards;
2021-12-02 23:24:07.225 CET [24820] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-02 23:24:07.225 CET [24820] LOG:  terminating any other active server processes
2021-12-02 23:24:07.226 CET [28320] WARNING:  terminating connection because of crash of another server process
2021-12-02 23:24:07.226 CET [28320] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-02 23:24:07.226 CET [28320] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-02 23:24:07.418 CET [24820] LOG:  all server processes terminated; reinitializing
2021-12-02 23:24:07.597 CET [21144] LOG:  database system was interrupted; last known up at 2021-12-02 23:19:20 CET
2021-12-02 23:24:23.140 CET [21144] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-02 23:24:23.264 CET [21144] LOG:  redo starts at 0/17960D0
2021-12-02 23:24:23.294 CET [21144] LOG:  invalid record length at 0/17AF0C8: wanted 24, got 0
2021-12-02 23:24:23.294 CET [21144] LOG:  redo done at 0/17AF090
2021-12-02 23:24:23.294 CET [21144] LOG:  last completed transaction was at log time 2021-12-02 23:23:50.765713+01
2021-12-02 23:24:25.559 CET [24820] LOG:  database system is ready to accept connections
2021-12-02 23:25:33.930 CET [24820] LOG:  worker process: logical replication launcher (PID 27356) was terminated by exception 0xC000013A
2021-12-02 23:25:33.930 CET [24820] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-02 23:25:33.930 CET [24820] LOG:  terminating any other active server processes
2021-12-02 23:25:33.931 CET [8968] WARNING:  terminating connection because of crash of another server process
2021-12-02 23:25:33.931 CET [8968] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-02 23:25:33.931 CET [8968] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-02 23:25:33.933 CET [24820] LOG:  statistics collector process (PID 13440) was terminated by exception 0xC000013A
2021-12-02 23:25:33.933 CET [24820] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-02 23:25:33.943 CET [24820] LOG:  all server processes terminated; reinitializing
2021-12-02 23:25:34.219 CET [20148] LOG:  database system was interrupted; last known up at 2021-12-02 23:24:25 CET
2021-12-02 23:25:34.274 CET [24820] LOG:  startup process (PID 20148) was terminated by exception 0xC000013A
2021-12-02 23:25:34.274 CET [24820] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-02 23:25:34.274 CET [24820] LOG:  aborting startup due to startup process failure
^C2021-12-03 10:51:32.437 CET [25920] LOG:  listening on IPv6 address "::1", port 15000
2021-12-03 10:51:32.437 CET [25920] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-03 10:51:33.425 CET [27960] LOG:  database system was interrupted; last known up at 2021-12-02 23:24:25 CET
2021-12-03 10:51:40.801 CET [27960] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-03 10:51:42.178 CET [27960] LOG:  redo starts at 0/17AF138
2021-12-03 10:51:42.178 CET [27960] LOG:  invalid record length at 0/17AF170: wanted 24, got 0
2021-12-03 10:51:42.179 CET [27960] LOG:  redo done at 0/17AF138
2021-12-03 10:51:43.088 CET [25920] LOG:  database system is ready to accept connections
2021-12-03 10:52:28.755 CET [5128] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 10:52:28.755 CET [5128] DETAIL:  Key (id)=(6adf6d95-9f77-4d11-a5ea-984f70fd9377) already exists.
2021-12-03 10:52:28.755 CET [5128] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 10:52:29.010 CET [5128] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:52:54.616 CET [20908] ERROR:  syntax error at or near "d10c2" at character 41
2021-12-03 10:52:54.616 CET [20908] STATEMENT:  INSERT INTO decks (id, name) VALUES (867d10c2-b8a6-4257-8f02-74617f607a4e, New Deck)
2021-12-03 10:52:54.904 CET [20908] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:53:31.443 CET [22816] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:54:52.545 CET [22308] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:55:08.229 CET [17312] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:58:37.293 CET [16332] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 10:58:37.293 CET [16332] DETAIL:  Key (id)=(fd05cdc8-99aa-4163-a329-95a92f334765) already exists.
2021-12-03 10:58:37.293 CET [16332] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 10:58:38.076 CET [1592] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 10:58:38.076 CET [1592] DETAIL:  Key (id)=(ba02fd81-3c9d-4077-8aba-6579087a92f1) already exists.
2021-12-03 10:58:38.076 CET [1592] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 10:58:47.374 CET [16332] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:58:47.374 CET [10364] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:58:47.374 CET [1592] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 10:58:47.374 CET [12852] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:01:43.529 CET [10412] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:02:58.718 CET [13220] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:29:53.152 CET [27076] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 11:29:53.152 CET [27076] DETAIL:  Key (id)=(e364a72b-f062-4643-8f4c-32bd147b24a0) already exists.
2021-12-03 11:29:53.152 CET [27076] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 11:29:54.144 CET [16436] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 11:29:54.144 CET [16436] DETAIL:  Key (id)=(1ea2ad6c-d57c-48b5-b8f9-851390ac2bd3) already exists.
2021-12-03 11:29:54.144 CET [16436] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 11:30:02.272 CET [27076] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:30:02.272 CET [29040] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:30:02.272 CET [16436] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:30:02.272 CET [13792] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:30:43.577 CET [20292] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 11:30:43.577 CET [20292] DETAIL:  Key (id)=(d715cda9-16da-4c29-a53e-803c009f2cf9) already exists.
2021-12-03 11:30:43.577 CET [20292] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 11:30:44.661 CET [15172] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 11:30:44.661 CET [15172] DETAIL:  Key (id)=(b5348de2-565d-4cba-9253-edaa003db7e0) already exists.
2021-12-03 11:30:44.661 CET [15172] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 11:30:52.611 CET [2800] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:30:52.611 CET [15172] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:30:52.611 CET [20292] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:30:52.611 CET [23644] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:31:17.297 CET [28468] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 11:31:17.297 CET [28468] DETAIL:  Key (id)=(147adfa5-e627-4d87-be53-42bfbe610d95) already exists.
2021-12-03 11:31:17.297 CET [28468] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 11:31:18.506 CET [11276] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 11:31:18.506 CET [11276] DETAIL:  Key (id)=(3d74a354-573b-4cab-abf4-3c19b1e5b4a3) already exists.
2021-12-03 11:31:18.506 CET [11276] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 11:31:29.349 CET [28468] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:31:29.350 CET [11276] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:31:29.350 CET [20204] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:31:29.350 CET [9164] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:48:06.907 CET [15388] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:48:06.907 CET [15388] LOG:  unexpected EOF on client connection with an open transaction
2021-12-03 11:48:49.894 CET [26184] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-03 11:48:49.894 CET [26184] DETAIL:  Key (username)=(rasebdon) already exists.
2021-12-03 11:48:49.894 CET [26184] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES ('dfdd9514-836a-4ab6-a3a2-4fce1be95662', 'rasebdon', 'hash', 20, 5, 25, False)
2021-12-03 11:49:00.412 CET [26184] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:49:45.253 CET [10348] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:49:45.253 CET [10348] LOG:  unexpected EOF on client connection with an open transaction
2021-12-03 11:50:20.532 CET [29692] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-03 11:50:20.532 CET [29692] DETAIL:  Key (username)=(rasebdon) already exists.
2021-12-03 11:50:20.532 CET [29692] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin) 
	                VALUES ('fd67f540-ff17-4f00-9860-6cabbe54d291', 'rasebdon', 'hash', 20, 5, 25, False)
2021-12-03 11:50:20.853 CET [29692] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:51:11.216 CET [23036] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:51:25.839 CET [2584] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:51:38.595 CET [19580] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 11:51:38.595 CET [19580] DETAIL:  Key (id)=(9a47e6a7-c731-4efd-b8a1-e31411acf8af) already exists.
2021-12-03 11:51:38.595 CET [19580] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 11:51:39.393 CET [25628] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 11:51:39.393 CET [25628] DETAIL:  Key (id)=(fbcc6cb7-a251-43c5-ad27-f0ebd3a8a8bd) already exists.
2021-12-03 11:51:39.393 CET [25628] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 11:51:50.134 CET [19580] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:51:50.134 CET [25628] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:51:50.134 CET [23340] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 11:51:50.134 CET [29400] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:05:18.636 CET [14700] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 12:05:18.636 CET [14700] DETAIL:  Key (id)=(57ae7b0d-1823-4c16-8feb-7485f50d90c1) already exists.
2021-12-03 12:05:18.636 CET [14700] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 12:05:19.966 CET [16180] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 12:05:19.966 CET [16180] DETAIL:  Key (id)=(8d791879-09f2-4175-bb88-8e50ed05d97b) already exists.
2021-12-03 12:05:19.966 CET [16180] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 12:05:27.947 CET [14700] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:05:27.947 CET [16180] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:05:27.947 CET [23036] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:05:27.948 CET [16912] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:06:41.676 CET [10292] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:07:29.213 CET [14716] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:08:10.727 CET [16948] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:08:49.812 CET [22304] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:11:00.509 CET [16444] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:12:30.432 CET [27456] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:13:06.271 CET [7340] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:13:13.507 CET [20588] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:13:50.568 CET [3004] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:14:03.813 CET [2724] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 12:14:03.813 CET [2724] DETAIL:  Key (id)=(2e6a5444-cf68-4c06-b3a2-e196cb863343) already exists.
2021-12-03 12:14:03.813 CET [2724] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 12:14:04.596 CET [22128] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 12:14:04.596 CET [22128] DETAIL:  Key (id)=(1146ecae-1fe3-49e9-983f-79de14b920be) already exists.
2021-12-03 12:14:04.596 CET [22128] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 12:14:10.561 CET [29636] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:14:10.561 CET [2724] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:14:10.561 CET [22128] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:14:10.561 CET [29288] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:40:04.418 CET [16940] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:46:14.595 CET [19804] ERROR:  syntax error at or near "d" at character 64
2021-12-03 12:46:14.595 CET [19804] STATEMENT:  SELECT FROM user_cards WHERE card_instance_id=f3afed00-4018-4e6d-a1e4-57c6cbae7332
2021-12-03 12:46:14.825 CET [19804] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:46:42.938 CET [14100] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:47:08.546 CET [25100] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:49:22.148 CET [14320] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:50:00.804 CET [23160] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:50:10.221 CET [10712] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 12:51:03.991 CET [18796] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:24:52.549 CET [8436] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 13:24:52.549 CET [8436] DETAIL:  Key (id)=(8d18e94c-c5eb-4eff-834c-3cc61af96888) already exists.
2021-12-03 13:24:52.549 CET [8436] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 13:24:53.260 CET [19312] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 13:24:53.260 CET [19312] DETAIL:  Key (id)=(0c73bc0a-a35e-4f9b-8670-7c9df3330241) already exists.
2021-12-03 13:24:53.260 CET [19312] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 13:24:58.472 CET [21872] ERROR:  syntax error at or near ";" at character 135
2021-12-03 13:24:58.472 CET [21872] STATEMENT:  INSERT INTO package_cards (package_id, card_id) VALUES ('1800b254-9990-47df-abf9-1c6136e6acbc', '79e173fb-36a7-482f-8579-7d94f43907d3';
2021-12-03 13:24:58.794 CET [21872] ERROR:  syntax error at or near ";" at character 135
2021-12-03 13:24:58.794 CET [21872] STATEMENT:  INSERT INTO package_cards (package_id, card_id) VALUES ('248d04f9-087b-4073-accd-5b7e35012f9e', 'cc0211a9-a794-4cdd-a362-cfaa3677aebb';
2021-12-03 13:24:59.039 CET [21872] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2021-12-03 13:24:59.039 CET [21872] DETAIL:  Key (id)=(afd8bb87-1601-40f0-9f5d-6c358518ebe0) already exists.
2021-12-03 13:24:59.039 CET [21872] STATEMENT:  INSERT INTO packages (id, name, description, cost) 
	                    VALUES ($1, $2, $3, $4)
2021-12-03 13:24:59.040 CET [21872] ERROR:  syntax error at or near "f0" at character 49
2021-12-03 13:24:59.040 CET [21872] STATEMENT:  SELECT * FROM packages WHERE id=afd8bb87-1601-40f0-9f5d-6c358518ebe0
2021-12-03 13:24:59.041 CET [21872] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:24:59.041 CET [21872] STATEMENT:  DELETE FROM packages
2021-12-03 13:24:59.042 CET [21872] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:24:59.042 CET [21872] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                    VALUES ('3a528183-0db1-4aac-874b-a3a6f059e44c', 'Card1', 'This is a card1!', 10,
	                    0, 0, 8, 1)
2021-12-03 13:24:59.043 CET [21872] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:24:59.043 CET [21872] STATEMENT:  DELETE FROM packages
2021-12-03 13:25:01.164 CET [27956] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:25:01.164 CET [8436] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:25:01.164 CET [19312] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:25:01.165 CET [21872] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:25:01.165 CET [4952] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:25:01.165 CET [5928] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:26:12.825 CET [3464] ERROR:  syntax error at or near "b8d54be" at character 34
2021-12-03 13:26:12.825 CET [3464] STATEMENT:  SELECT * FROM packages WHERE id=1b8d54be-fcbb-4dad-8cc9-8cd7fdb0a1a3
2021-12-03 13:26:13.652 CET [3464] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2021-12-03 13:26:13.652 CET [3464] DETAIL:  Key (id)=(a96146b4-87e1-4e5c-bdd8-600428692c9d) already exists.
2021-12-03 13:26:13.652 CET [3464] STATEMENT:  INSERT INTO packages (id, name, description, cost) 
	                    VALUES ($1, $2, $3, $4)
2021-12-03 13:26:13.654 CET [3464] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:13.654 CET [3464] STATEMENT:  SELECT * FROM packages WHERE id='a96146b4-87e1-4e5c-bdd8-600428692c9d'
2021-12-03 13:26:13.655 CET [3464] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:13.655 CET [3464] STATEMENT:  DELETE FROM packages
2021-12-03 13:26:13.656 CET [3464] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:13.656 CET [3464] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                    VALUES ('6a8cd9a5-82d8-4f5e-8a4d-d755f25ddfaa', 'Card1', 'This is a card1!', 10,
	                    0, 0, 8, 1)
2021-12-03 13:26:13.657 CET [3464] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:13.657 CET [3464] STATEMENT:  DELETE FROM packages
2021-12-03 13:26:13.688 CET [3464] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:26:38.740 CET [10104] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2021-12-03 13:26:38.740 CET [10104] DETAIL:  Key (id)=(efddc8c2-0b16-448a-b249-3f26ba004a96) already exists.
2021-12-03 13:26:38.740 CET [10104] STATEMENT:  INSERT INTO packages (id, name, description, cost) 
	                    VALUES ($1, $2, $3, $4)
2021-12-03 13:26:38.786 CET [10104] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:38.786 CET [10104] STATEMENT:  SELECT * FROM packages WHERE id='efddc8c2-0b16-448a-b249-3f26ba004a96'
2021-12-03 13:26:38.789 CET [10104] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:38.789 CET [10104] STATEMENT:  DELETE FROM packages
2021-12-03 13:26:38.790 CET [10104] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:38.790 CET [10104] STATEMENT:  INSERT INTO cards (id, name, description, damage, type, element, race, rarity) 
	                    VALUES ('52725712-50d2-4b1a-a48f-e7e23d55da89', 'Card1', 'This is a card1!', 10,
	                    0, 0, 8, 1)
2021-12-03 13:26:38.791 CET [10104] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-12-03 13:26:38.791 CET [10104] STATEMENT:  DELETE FROM packages
2021-12-03 13:26:38.822 CET [10104] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:28:24.679 CET [11200] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2021-12-03 13:28:24.679 CET [11200] DETAIL:  Key (id)=(e87d4b85-269d-43e3-aea9-886a63cf6e30) already exists.
2021-12-03 13:28:24.679 CET [11200] STATEMENT:  INSERT INTO packages (id, name, description, cost) 
	                    VALUES ($1, $2, $3, $4)
2021-12-03 13:28:25.090 CET [11200] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:28:45.208 CET [25348] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2021-12-03 13:28:45.208 CET [25348] DETAIL:  Key (id)=(7e189785-3ac2-4a59-93b4-c5749d218eda) already exists.
2021-12-03 13:28:45.208 CET [25348] STATEMENT:  INSERT INTO packages (id, name, description, cost) 
	                    VALUES ($1, $2, $3, $4)
2021-12-03 13:28:45.808 CET [25348] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:29:45.182 CET [1792] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2021-12-03 13:29:45.182 CET [1792] DETAIL:  Key (id)=(1b27740a-4d54-414a-8b98-1690f74484f3) already exists.
2021-12-03 13:29:45.182 CET [1792] STATEMENT:  INSERT INTO packages (id, name, description, cost) 
	                    VALUES ($1, $2, $3, $4)
2021-12-03 13:30:33.934 CET [1792] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:31:35.775 CET [27540] ERROR:  duplicate key value violates unique constraint "packages_pkey"
2021-12-03 13:31:35.775 CET [27540] DETAIL:  Key (id)=(859d4ca6-8d83-4987-a97e-6fe0f83fc19f) already exists.
2021-12-03 13:31:35.775 CET [27540] STATEMENT:  INSERT INTO packages (id, name, description, cost) 
	                    VALUES ($1, $2, $3, $4)
2021-12-03 13:31:53.445 CET [27540] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:33:14.980 CET [16464] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:33:14.980 CET [16464] LOG:  unexpected EOF on client connection with an open transaction
2021-12-03 13:33:37.774 CET [14700] ERROR:  column "card_id" does not exist at character 62
2021-12-03 13:33:37.774 CET [14700] HINT:  There is a column named "card_id" in table "package_cards", but it cannot be referenced from this part of the query.
2021-12-03 13:33:37.774 CET [14700] STATEMENT:  INSERT INTO package_cards (package_id, card_id) VALUES ($1, @card_id)
2021-12-03 13:33:38.055 CET [14700] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:34:09.691 CET [28008] ERROR:  column "card_id" does not exist at character 62
2021-12-03 13:34:09.691 CET [28008] HINT:  There is a column named "card_id" in table "package_cards", but it cannot be referenced from this part of the query.
2021-12-03 13:34:09.691 CET [28008] STATEMENT:  INSERT INTO package_cards (package_id, card_id) VALUES ($1, @card_id)
2021-12-03 13:35:18.102 CET [28008] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:35:30.273 CET [13084] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:36:03.756 CET [22832] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:37:23.887 CET [25920] LOG:  server process (PID 21640) was terminated by exception 0xC000013A
2021-12-03 13:37:23.887 CET [25920] DETAIL:  Failed process was running: SELECT card_id FROM package_cards;
2021-12-03 13:37:23.887 CET [25920] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-03 13:37:23.887 CET [25920] LOG:  terminating any other active server processes
2021-12-03 13:37:23.890 CET [26544] WARNING:  terminating connection because of crash of another server process
2021-12-03 13:37:23.890 CET [26544] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-03 13:37:23.890 CET [26544] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-03 13:37:24.106 CET [25920] LOG:  all server processes terminated; reinitializing
2021-12-03 13:37:24.586 CET [29204] LOG:  database system was interrupted; last known up at 2021-12-03 13:36:47 CET
2021-12-03 13:37:28.572 CET [25920] LOG:  startup process (PID 29204) was terminated by exception 0xC000013A
2021-12-03 13:37:28.572 CET [25920] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-03 13:37:28.572 CET [25920] LOG:  aborting startup due to startup process failure
^C2021-12-03 13:37:37.550 CET [11976] LOG:  listening on IPv6 address "::1", port 15000
2021-12-03 13:37:37.550 CET [11976] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-03 13:37:38.625 CET [23388] LOG:  database system was interrupted; last known up at 2021-12-03 13:36:47 CET
2021-12-03 13:37:47.757 CET [23388] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-03 13:37:48.852 CET [23388] LOG:  redo starts at 0/1940710
2021-12-03 13:37:48.852 CET [23388] LOG:  invalid record length at 0/19407F0: wanted 24, got 0
2021-12-03 13:37:48.852 CET [23388] LOG:  redo done at 0/19407B8
2021-12-03 13:37:50.163 CET [11976] LOG:  database system is ready to accept connections
2021-12-03 13:38:01.845 CET [22192] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:40:10.738 CET [21932] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-03 13:40:10.738 CET [21932] DETAIL:  Key (id)=(0122192b-daf9-4d35-adba-5cea4eb1236c) already exists.
2021-12-03 13:40:10.738 CET [21932] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-03 13:40:11.418 CET [25336] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-03 13:40:11.418 CET [25336] DETAIL:  Key (id)=(25da1f71-1a8b-413b-be79-f660dabd16fd) already exists.
2021-12-03 13:40:11.418 CET [25336] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-03 13:40:20.079 CET [21932] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:40:20.079 CET [13792] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:40:20.079 CET [25336] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:40:20.079 CET [29552] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:40:20.079 CET [19164] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 13:40:20.079 CET [20276] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-03 14:14:48.714 CET [11976] LOG:  server process (PID 21632) was terminated by exception 0xC000013A
2021-12-03 14:14:48.714 CET [11976] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-03 14:14:48.714 CET [11976] LOG:  terminating any other active server processes
2021-12-03 14:14:48.715 CET [5656] WARNING:  terminating connection because of crash of another server process
2021-12-03 14:14:48.715 CET [5656] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-03 14:14:48.715 CET [5656] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-03 14:14:48.898 CET [11976] LOG:  all server processes terminated; reinitializing
^C2021-12-03 14:14:49.200 CET [6156] LOG:  database system was interrupted; last known up at 2021-12-03 13:42:54 CET
2021-12-07 13:48:16.828 CET [27360] LOG:  listening on IPv6 address "::1", port 15000
2021-12-07 13:48:16.828 CET [27360] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-07 13:48:17.754 CET [23772] LOG:  database system was interrupted; last known up at 2021-12-03 13:42:54 CET
2021-12-07 13:48:26.774 CET [23772] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-07 13:48:27.169 CET [23772] LOG:  redo starts at 0/1961C68
2021-12-07 13:48:27.170 CET [23772] LOG:  invalid record length at 0/1961D48: wanted 24, got 0
2021-12-07 13:48:27.170 CET [23772] LOG:  redo done at 0/1961D10
2021-12-07 13:48:28.028 CET [27360] LOG:  database system is ready to accept connections
2021-12-07 13:49:54.208 CET [13144] ERROR:  relation "users" does not exist
2021-12-07 13:49:54.208 CET [13144] STATEMENT:  ALTER TABLE users ADD COLUMN bio VARCHAR, ADD COLUMN image VARCHAR;
2021-12-07 13:49:57.259 CET [13144] ERROR:  relation "users" does not exist
2021-12-07 13:49:57.259 CET [13144] STATEMENT:  ALTER TABLE users ADD COLUMN bio VARCHAR, ADD COLUMN image VARCHAR;
2021-12-07 13:50:05.201 CET [22152] FATAL:  role "mockdb" does not exist
2021-12-07 13:50:23.087 CET [27360] LOG:  received fast shutdown request
2021-12-07 13:50:23.467 CET [27360] LOG:  aborting any active transactions
2021-12-07 13:50:23.472 CET [27360] LOG:  worker process: logical replication launcher (PID 26568) exited with exit code 1
2021-12-07 13:50:23.472 CET [27208] LOG:  shutting down
2021-12-07 13:50:24.350 CET [27360] LOG:  database system is shut down
2021-12-07 14:01:39.784 CET [13536] LOG:  listening on IPv6 address "::1", port 15000
2021-12-07 14:01:39.785 CET [13536] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-07 14:01:40.687 CET [14324] LOG:  database system was shut down at 2021-12-07 13:50:24 CET
2021-12-07 14:01:41.242 CET [13536] LOG:  database system is ready to accept connections
2021-12-07 14:05:18.734 CET [4368] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-07 14:05:18.734 CET [4368] DETAIL:  Key (id)=(ea78b597-ba4c-4ef8-b505-6c77a0cb8c8b) already exists.
2021-12-07 14:05:18.734 CET [4368] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-07 14:05:19.642 CET [26064] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-07 14:05:19.642 CET [26064] DETAIL:  Key (id)=(cbde260c-9b89-4694-94c9-ccf4056d7d1c) already exists.
2021-12-07 14:05:19.642 CET [26064] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-07 14:05:29.035 CET [9128] ERROR:  syntax error at or near "bio" at character 83
2021-12-07 14:05:29.035 CET [9128] STATEMENT:  UPDATE users SET coins=$1, elo=$2, admin=$3, played_games=$4
	                    bio=$5, image=$6
	                    WHERE id=$7
2021-12-07 14:05:29.251 CET [4368] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:05:29.251 CET [18332] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:05:29.252 CET [21828] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:05:29.252 CET [18480] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:05:29.252 CET [26064] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:05:29.252 CET [9128] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:07:17.390 CET [9576] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:08:43.924 CET [29756] ERROR:  syntax error at or near "playing" at character 206
2021-12-07 14:08:43.924 CET [29756] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('b457317d-689c-4275-8935-5d1cc6c2f540', 'test', 'hash', 50, 50,
	                50, False, Im playing MTCG!, :-));
2021-12-07 14:08:43.992 CET [29756] ERROR:  syntax error at or near "playing" at character 206
2021-12-07 14:08:43.992 CET [29756] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('4830f2b6-6135-43ba-a2aa-6cea19cc1033', 'test', 'hash', 50, 50,
	                50, False, Im playing MTCG!, :-));
2021-12-07 14:08:43.994 CET [29756] ERROR:  syntax error at or near "playing" at character 206
2021-12-07 14:08:43.994 CET [29756] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('3f7d0188-9e62-4896-b45c-c6fa9731cd80', 'test', 'hash', 50, 50,
	                50, False, Im playing MTCG!, :-));
2021-12-07 14:08:44.531 CET [29756] ERROR:  syntax error at or near "playing" at character 206
2021-12-07 14:08:44.531 CET [29756] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('f790b6e2-ee97-4255-95dd-9fe99e9d664d', 'test', 'hash', 50, 50,
	                50, False, Im playing MTCG!, :-));
2021-12-07 14:08:44.533 CET [29756] ERROR:  syntax error at or near "playing" at character 206
2021-12-07 14:08:44.533 CET [29756] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('29bfc687-66b6-4c37-9411-a8b013fccaa2', 'test', 'hash', 50, 50,
	                50, False, Im playing MTCG!, :-));
2021-12-07 14:08:44.594 CET [29756] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:09:23.614 CET [1144] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:09:23.614 CET [1144] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:09:23.614 CET [1144] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('1b331864-df2a-4a59-95ba-ba2799b13041', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:09:23.737 CET [1144] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:09:23.737 CET [1144] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:09:23.737 CET [1144] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('ac847fe1-aa91-4bc8-b560-1a5775e23a41', 'test', 'hash', 50, 50,
	                50, False, ' Im playing MTCG! ', ' :-) ')
2021-12-07 14:09:23.738 CET [1144] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:09:23.738 CET [1144] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:09:23.738 CET [1144] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('cfee50ae-4fe7-439c-ba8b-c4b89342573f', 'test', 'hash', 50, 50,
	                50, False, ' Im playing MTCG! ', ' :-) ')
2021-12-07 14:09:23.856 CET [1144] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:09:23.856 CET [1144] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:09:23.856 CET [1144] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('def6d8f3-28ae-4ddb-b65c-f590728834a6', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:09:23.858 CET [1144] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:09:23.858 CET [1144] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:09:23.858 CET [1144] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('3b77247f-b1a6-4e6a-b7f6-4bc9ecd0c892', 'test', 'hash', 50, 50,
	                50, False, ' Im playing MTCG! ', ' :-) ')
2021-12-07 14:09:23.911 CET [1144] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:09:51.329 CET [22504] ERROR:  relation "users" does not exist at character 13
2021-12-07 14:09:51.329 CET [22504] STATEMENT:  DELETE FROM users;
2021-12-07 14:10:12.523 CET [7036] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-07 14:10:12.523 CET [7036] DETAIL:  Key (id)=(c57945db-7740-43aa-8f17-d0a9a25406eb) already exists.
2021-12-07 14:10:12.523 CET [7036] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-07 14:10:14.414 CET [500] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-07 14:10:14.414 CET [500] DETAIL:  Key (id)=(7887e1e0-9c44-43cf-a9f0-77bbed76cbf8) already exists.
2021-12-07 14:10:14.414 CET [500] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-07 14:10:25.408 CET [27748] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:10:25.408 CET [27748] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:10:25.408 CET [27748] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('4401fb75-345a-4f11-8542-fce9292281d9', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:10:25.480 CET [27748] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:10:25.480 CET [27748] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:10:25.480 CET [27748] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('e8faa931-37b1-406e-bb13-0ad3ab9143b7', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:10:25.481 CET [27748] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:10:25.481 CET [27748] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:10:25.481 CET [27748] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('29af1f1e-83b9-481b-985f-6a33c351b0d7', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:10:25.571 CET [27748] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:10:25.571 CET [27748] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:10:25.571 CET [27748] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('519e7282-8952-487d-97af-b8540b234a2e', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:10:25.573 CET [27748] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:10:25.573 CET [27748] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:10:25.573 CET [27748] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('acc539c1-990b-476f-a710-82e9559f644a', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:10:25.892 CET [7036] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:10:25.892 CET [27748] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:10:25.892 CET [3480] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:10:25.892 CET [500] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:10:25.892 CET [29640] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:10:25.892 CET [16584] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:13:00.394 CET [17940] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:13:00.394 CET [17940] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:13:00.394 CET [17940] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('075e0a26-4e15-44b4-8c3c-636137777ad0', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:13:01.280 CET [17940] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:13:01.280 CET [17940] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:13:01.280 CET [17940] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('8bd64ee3-2870-493b-aec9-9e6a1b671099', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:13:01.370 CET [17940] ERROR:  syntax error at or near "bio" at character 83
2021-12-07 14:13:01.370 CET [17940] STATEMENT:  UPDATE users SET coins=$1, elo=$2, admin=$3, played_games=$4
	                    bio=$5, image=$6
	                    WHERE id=$7
2021-12-07 14:13:01.476 CET [17940] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:14:50.803 CET [14708] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:14:50.803 CET [14708] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:14:50.803 CET [14708] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('71abbf58-0835-4d24-9b62-1000b5d0d895', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:14:51.093 CET [14708] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:16:44.126 CET [28860] ERROR:  syntax error at or near "bio" at character 83
2021-12-07 14:16:44.126 CET [28860] STATEMENT:  UPDATE users SET coins=$1, elo=$2, admin=$3, played_games=$4
	                    bio=$5, image=$6
	                    WHERE id=$7
2021-12-07 14:16:44.264 CET [28860] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:17:20.756 CET [23468] ERROR:  syntax error at or near "bio" at character 83
2021-12-07 14:17:20.756 CET [23468] STATEMENT:  UPDATE users SET coins=$1, elo=$2, admin=$3, played_games=$4
	                    bio=$5, image=$6
	                    WHERE id=$7
2021-12-07 14:17:20.996 CET [23468] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:17:40.740 CET [11364] ERROR:  syntax error at or near "bio" at character 83
2021-12-07 14:17:40.740 CET [11364] STATEMENT:  UPDATE users SET coins=$1, elo=$2, admin=$3, played_games=$4
	                    bio=$5, image=$6
	                    WHERE id=$7
2021-12-07 14:17:47.347 CET [11364] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:17:57.996 CET [21596] ERROR:  duplicate key value violates unique constraint "unqiue_username"
2021-12-07 14:17:57.996 CET [21596] DETAIL:  Key (username)=(test) already exists.
2021-12-07 14:17:57.996 CET [21596] STATEMENT:  INSERT INTO users (id, username, hash, coins, elo, played_games, admin, bio, image) 
	                VALUES ('9792e567-f109-4b73-9033-a8d87ba0e3b6', 'test', 'hash', 50, 50,
	                50, False, 'Im playing MTCG!', ':-)')
2021-12-07 14:17:58.772 CET [21596] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:18:45.424 CET [18752] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:18:50.979 CET [22424] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-07 14:18:50.979 CET [22424] DETAIL:  Key (id)=(3fc07b39-f79e-4223-9ffd-43b2d19f3108) already exists.
2021-12-07 14:18:50.979 CET [22424] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-07 14:18:51.713 CET [27616] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-07 14:18:51.713 CET [27616] DETAIL:  Key (id)=(162dfa50-8e1c-4d4a-8ee2-71350794d59c) already exists.
2021-12-07 14:18:51.713 CET [27616] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-07 14:19:01.063 CET [22424] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:19:01.063 CET [13316] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:19:01.063 CET [1884] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:19:01.063 CET [16264] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:19:01.063 CET [27616] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:19:01.063 CET [24928] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 14:33:36.096 CET [13536] LOG:  server process (PID 280) was terminated by exception 0xC000013A
2021-12-07 14:33:36.096 CET [13536] DETAIL:  Failed process was running: DELETE FROM users;
2021-12-07 14:33:36.096 CET [13536] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-07 14:33:36.096 CET [13536] LOG:  terminating any other active server processes
2021-12-07 14:33:36.097 CET [12024] WARNING:  terminating connection because of crash of another server process
2021-12-07 14:33:36.097 CET [12024] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-07 14:33:36.097 CET [12024] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-07 14:33:36.308 CET [13536] LOG:  all server processes terminated; reinitializing
2021-12-07 14:33:36.496 CET [30424] LOG:  database system was interrupted; last known up at 2021-12-07 14:21:46 CET
2021-12-07 14:33:39.167 CET [13536] LOG:  startup process (PID 30424) was terminated by exception 0xC000013A
2021-12-07 14:33:39.167 CET [13536] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-07 14:33:39.167 CET [13536] LOG:  aborting startup due to startup process failure
^C2021-12-07 17:43:34.373 CET [13588] LOG:  listening on IPv6 address "::1", port 15000
2021-12-07 17:43:34.373 CET [13588] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-07 17:43:35.307 CET [10376] LOG:  database system was interrupted; last known up at 2021-12-07 14:21:46 CET
2021-12-07 17:43:44.979 CET [10376] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-07 17:43:45.617 CET [10376] LOG:  redo starts at 0/19E1340
2021-12-07 17:43:45.619 CET [10376] LOG:  invalid record length at 0/19E1420: wanted 24, got 0
2021-12-07 17:43:45.619 CET [10376] LOG:  redo done at 0/19E13E8
2021-12-07 17:43:47.223 CET [13588] LOG:  database system is ready to accept connections
2021-12-07 17:45:48.978 CET [26084] ERROR:  relation "users" does not exist
2021-12-07 17:45:48.978 CET [26084] STATEMENT:  ALTER TABLE users ADD COLUMN wins INTEGER DEFAULT 0 NOT NULL;
2021-12-07 17:46:09.298 CET [13588] LOG:  server process (PID 31356) was terminated by exception 0xC000013A
2021-12-07 17:46:09.298 CET [13588] DETAIL:  Failed process was running: ALTER TABLE users ADD COLUMN wins INTEGER DEFAULT 0 NOT NULL;
2021-12-07 17:46:09.298 CET [13588] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-07 17:46:09.298 CET [13588] LOG:  terminating any other active server processes
2021-12-07 17:46:09.299 CET [24916] WARNING:  terminating connection because of crash of another server process
2021-12-07 17:46:09.299 CET [24916] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-07 17:46:09.299 CET [24916] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-07 17:46:09.426 CET [13588] LOG:  all server processes terminated; reinitializing
2021-12-07 17:46:09.643 CET [7916] LOG:  database system was interrupted; last known up at 2021-12-07 17:43:46 CET
2021-12-07 17:46:15.080 CET [13588] LOG:  startup process (PID 7916) was terminated by exception 0xC000013A
2021-12-07 17:46:15.080 CET [13588] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-07 17:46:15.080 CET [13588] LOG:  aborting startup due to startup process failure
^C2021-12-07 17:47:33.089 CET [22032] LOG:  listening on IPv6 address "::1", port 15000
2021-12-07 17:47:33.089 CET [22032] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-07 17:47:33.826 CET [28056] LOG:  database system was interrupted; last known up at 2021-12-07 17:43:46 CET
2021-12-07 17:47:41.706 CET [28056] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-07 17:47:43.327 CET [28056] LOG:  redo starts at 0/19E1490
2021-12-07 17:47:43.782 CET [28056] LOG:  invalid record length at 0/1A12A68: wanted 24, got 0
2021-12-07 17:47:43.782 CET [28056] LOG:  redo done at 0/1A11D28
2021-12-07 17:47:43.784 CET [28056] LOG:  last completed transaction was at log time 2021-12-07 17:45:58.588191+01
2021-12-07 17:47:46.808 CET [22032] LOG:  database system is ready to accept connections
2021-12-07 17:51:06.634 CET [1404] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-07 17:51:06.634 CET [1404] DETAIL:  Key (id)=(dfc7c584-7950-425e-bbb3-2fa7fd8d66b9) already exists.
2021-12-07 17:51:06.634 CET [1404] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-07 17:51:07.742 CET [26528] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-07 17:51:07.742 CET [26528] DETAIL:  Key (id)=(b3427c76-5d93-4a06-b816-d89bf19ecc5d) already exists.
2021-12-07 17:51:07.742 CET [26528] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-07 17:51:20.031 CET [11384] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 17:51:20.031 CET [1404] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 17:51:20.031 CET [21400] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 17:51:20.031 CET [9476] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 17:51:20.031 CET [26528] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 17:51:20.031 CET [12984] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-07 18:01:25.236 CET [22032] LOG:  server process (PID 23664) was terminated by exception 0xC000013A
2021-12-07 18:01:25.236 CET [22032] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-07 18:01:25.236 CET [22032] LOG:  terminating any other active server processes
2021-12-07 18:01:25.237 CET [23984] WARNING:  terminating connection because of crash of another server process
2021-12-07 18:01:25.237 CET [23984] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-07 18:01:25.237 CET [23984] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-07 18:01:25.258 CET [22032] LOG:  statistics collector process (PID 17988) was terminated by exception 0xC000013A
2021-12-07 18:01:25.258 CET [22032] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-07 18:01:25.258 CET [22032] LOG:  all server processes terminated; reinitializing
2021-12-07 18:01:25.432 CET [18724] LOG:  database system was interrupted; last known up at 2021-12-07 17:52:55 CET
2021-12-07 18:01:25.931 CET [22032] LOG:  startup process (PID 18724) was terminated by exception 0xC000013A
2021-12-07 18:01:25.931 CET [22032] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-07 18:01:25.932 CET [22032] LOG:  aborting startup due to startup process failure
^C2021-12-09 16:14:17.975 CET [30540] LOG:  listening on IPv6 address "::1", port 15000
2021-12-09 16:14:17.975 CET [30540] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2021-12-09 16:14:19.234 CET [32688] LOG:  database system was interrupted; last known up at 2021-12-07 17:52:55 CET
2021-12-09 16:14:30.778 CET [32688] LOG:  database system was not properly shut down; automatic recovery in progress
2021-12-09 16:14:31.547 CET [32688] LOG:  redo starts at 0/1A39AA8
2021-12-09 16:14:32.013 CET [32688] LOG:  invalid record length at 0/1A3D728: wanted 24, got 0
2021-12-09 16:14:32.013 CET [32688] LOG:  redo done at 0/1A3D6F0
2021-12-09 16:14:32.034 CET [32688] LOG:  last completed transaction was at log time 2021-12-07 17:52:48.184632+01
2021-12-09 16:14:35.013 CET [30540] LOG:  database system is ready to accept connections
2021-12-09 16:14:58.652 CET [19680] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2021-12-09 16:14:58.652 CET [19680] DETAIL:  Key (id)=(7a6d21f6-0db5-49b2-8003-daf61019b4d4) already exists.
2021-12-09 16:14:58.652 CET [19680] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2021-12-09 16:14:59.601 CET [9636] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2021-12-09 16:14:59.601 CET [9636] DETAIL:  Key (id)=(6af4e491-7b14-49da-be20-09f266a00f46) already exists.
2021-12-09 16:14:59.601 CET [9636] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2021-12-09 16:15:10.604 CET [27484] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-09 16:15:10.604 CET [19680] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-09 16:15:10.604 CET [29292] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-09 16:15:10.604 CET [9636] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-09 16:15:10.605 CET [32080] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-09 16:15:10.605 CET [24192] LOG:  could not receive data from client: unrecognized winsock error 10054
2021-12-09 16:16:41.107 CET [30540] LOG:  server process (PID 31260) was terminated by exception 0xC000013A
2021-12-09 16:16:41.107 CET [30540] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-09 16:16:41.107 CET [30540] LOG:  terminating any other active server processes
2021-12-09 16:16:41.108 CET [18008] WARNING:  terminating connection because of crash of another server process
2021-12-09 16:16:41.108 CET [18008] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-12-09 16:16:41.108 CET [18008] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-12-09 16:16:41.336 CET [30540] LOG:  all server processes terminated; reinitializing
2021-12-09 16:16:41.492 CET [20736] LOG:  database system was interrupted; last known up at 2021-12-09 16:14:34 CET
2021-12-09 16:16:42.232 CET [30540] LOG:  startup process (PID 20736) was terminated by exception 0xC000013A
2021-12-09 16:16:42.232 CET [30540] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-12-09 16:16:42.232 CET [30540] LOG:  aborting startup due to startup process failure
^C2022-01-02 16:57:34.056 CET [3500] LOG:  listening on IPv6 address "::1", port 15000
2022-01-02 16:57:34.057 CET [3500] LOG:  listening on IPv4 address "127.0.0.1", port 15000
2022-01-02 16:57:34.926 CET [21672] LOG:  database system was interrupted; last known up at 2021-12-09 16:14:34 CET
2022-01-02 16:57:42.959 CET [21672] LOG:  database system was not properly shut down; automatic recovery in progress
2022-01-02 16:57:43.345 CET [21672] LOG:  redo starts at 0/1A3D798
2022-01-02 16:57:43.374 CET [21672] LOG:  invalid record length at 0/1A59DF0: wanted 24, got 0
2022-01-02 16:57:43.374 CET [21672] LOG:  redo done at 0/1A59DB8
2022-01-02 16:57:43.375 CET [21672] LOG:  last completed transaction was at log time 2021-12-09 16:15:10.391619+01
2022-01-02 16:57:46.065 CET [3500] LOG:  database system is ready to accept connections
2022-01-02 16:58:37.194 CET [26236] ERROR:  duplicate key value violates unique constraint "card_instances_pkey"
2022-01-02 16:58:37.194 CET [26236] DETAIL:  Key (id)=(2c4d2b7c-f5e8-4f43-ae9c-fad25188baac) already exists.
2022-01-02 16:58:37.194 CET [26236] STATEMENT:  INSERT INTO card_instances (id, card_id) VALUES ($1, $2)
2022-01-02 16:58:38.654 CET [20160] ERROR:  duplicate key value violates unique constraint "cards_pkey"
2022-01-02 16:58:38.654 CET [20160] DETAIL:  Key (id)=(ae701107-0047-4f9a-8bd9-f2f2f4f79075) already exists.
2022-01-02 16:58:38.654 CET [20160] STATEMENT:  INSERT INTO cards (id, name, description, type, damage, element, rarity, race)
	                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
2022-01-02 16:58:49.434 CET [21860] LOG:  could not receive data from client: unrecognized winsock error 10054
2022-01-02 16:58:49.434 CET [26236] LOG:  could not receive data from client: unrecognized winsock error 10054
2022-01-02 16:58:49.434 CET [20160] LOG:  could not receive data from client: unrecognized winsock error 10054
2022-01-02 16:58:49.435 CET [8568] LOG:  could not receive data from client: unrecognized winsock error 10054
2022-01-02 16:58:49.435 CET [16956] LOG:  could not receive data from client: unrecognized winsock error 10054
2022-01-02 16:58:49.435 CET [21544] LOG:  could not receive data from client: unrecognized winsock error 10054
2022-01-02 16:58:57.660 CET [3500] LOG:  server process (PID 12248) was terminated by exception 0xC000013A
2022-01-02 16:58:57.660 CET [3500] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2022-01-02 16:58:57.660 CET [3500] LOG:  terminating any other active server processes
2022-01-02 16:58:57.661 CET [5676] WARNING:  terminating connection because of crash of another server process
2022-01-02 16:58:57.661 CET [5676] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2022-01-02 16:58:57.661 CET [5676] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2022-01-02 16:58:57.858 CET [3500] LOG:  all server processes terminated; reinitializing
2022-01-02 16:58:58.009 CET [1064] LOG:  database system was interrupted; last known up at 2022-01-02 16:57:45 CET
2022-01-02 16:58:58.810 CET [3500] LOG:  startup process (PID 1064) was terminated by exception 0xC000013A
2022-01-02 16:58:58.810 CET [3500] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2022-01-02 16:58:58.810 CET [3500] LOG:  aborting startup due to startup process failure
^C